### ISSUE TITLE
TOC: Sort by req. id

### ISSUE THREAD

**Issue by marcoBanse** [useblocks/sphinxcontrib-needs#1]
Thanks for the great plugin. I propose an improvement: Please add an option to sort the TOC by requirement ID number. That should not be available for auto-generated req. IDs. In case of auto-generated req. IDs ordering by occurrence in source files would make sense.

**Comment by danwos** [comment]
Hey @marcoBanse ,

this issues is solved by version 1.4

For needlist I have added the param :sort_by: .
Valid options: id, status
