### ISSUE TITLE
Cannot overwrite status field

### ISSUE THREAD

**Issue by ubmarco** [useblocks/sphinxcontrib-needs#103]
Hi,
when trying to constrain the choices for the status field in `conf.py` like this:
```
def _status_choices(argument):
    """Choices for status needs property."""
    return directives.choice(argument, ('open', 'approved', 'implemented'))


needs_extra_options = {
    'status': _status_choices,
}
```
I get the following error:
```
Exception occurred:
  File "/home/marco/proj/.venv/lib/python3.8/site-packages/sphinxcontrib/needs/directives/need.py", line 120, in run
    return add_need(env.app, self.state, self.docname, self.lineno,
TypeError: add_need() got multiple values for keyword argument 'status'
```

That's because of the handling of `need_extra_options` in https://github.com/useblocks/sphinxcontrib-needs/blob/master/sphinxcontrib/needs/directives/need.py#L120.
This used to work, at least in version 0.3.10.

My proposal is to let users overwrite the field and take the overwritten field. Our usecase is to constrain the field so a need (e.g. requirement/spec) cannot have an arbitrary status.

**Comment by ubmarco** [comment]
I see there is also the option https://sphinxcontrib-needs.readthedocs.io/en/latest/configuration.html#needs-statuses.
Is that equivalent to my approach?

**Comment by danwos** [comment]
Yes, please use [needs_statuses]( https://sphinxcontrib-needs.readthedocs.io/en/latest/configuration.html#needs-statuses) or the new [needs_constraints](https://sphinxcontrib-needs.readthedocs.io/en/latest/configuration.html#needs-constraints).

I think there is no use case, where status-field configuration must be overwritten, if the above solutions are also available.
