### ISSUE TITLE
needs_title_from_content stops too early

### ISSUE THREAD

**Issue by ubmarco** [useblocks/sphinxcontrib-needs#106]
In my conf.py I have `needs_title_from_content = True`.
The need
```
.. vdaisa_req::
:id: VDAISA_REQ_01_02_07_01

Es existiert ein Maßnahmenplan bzw. Statusübersicht der Maßnahmenumsetzung.
```
renders to
![image](https://user-images.githubusercontent.com/839934/71515396-4a53af00-28a3-11ea-89c5-b6ffddd56821.png)

The sentence recognition does not understand that `max.` is an abbreviation.
I know it's a hard problem to properly detect sentence boundaries. Also needs could be used with any language, so it's even harder. To circumvent the problem, I propose a configurable whitelist of tokens that shall not mark the end of a sentence. For my example, I would configure:
```
needs_title_from_content_ignore_tokens = [
    'max.',
]
```

**Comment by danwos** [comment]
I think a solution via configuration option is not needed.

In such strange corner cases the user can simple set the title manually:
```
.. vdaisa_req:: Es existiert ein Maßnahmenplan bzw. Statusübersicht der Maßnahmenumsetzung.
:id: VDAISA_REQ_01_02_07_01

Es existiert ein Maßnahmenplan bzw. Statusübersicht der Maßnahmenumsetzung.
``` 
Or the user tries to avoid abbreviations.

So for me the workarounds are okay and I would like to not implement this, as a huge benefit is not really given.

**Comment by ubmarco** [comment]
I'm ok with the workaround to set the title manually.
