### ISSUE TITLE
need type CSS class name wrong

### ISSUE THREAD

**Issue by ubmarco** [useblocks/sphinxcontrib-needs#108]
I have the configuration
```
needs_types = [
    {'directive': 'vdaisa_chap', 'title': 'VDA ISA Chapter', 'prefix': 'VDAISA_CHAP', 'color': '#BFD8D2', 'style': 'node'},
    {'directive': 'vdaisa_req', 'title': 'VDA ISA Requirement', 'prefix': 'VDAISA_REQ', 'color': '#BFD8D2', 'style': 'node'},
]
```
In a rendered HTML, the CSS classes set for the need div look like this:
![image](https://user-images.githubusercontent.com/839934/71515967-93f1c900-28a6-11ea-8271-377183c37b54.png)

The logic seems to do the following:

1. Split the title on white spaces and create a class for each word.
2. Split the title on white spaces and create a class for each word in a lower case variant, prepending 'need-' for the first word.

I think both items are useless in my scenario. What I would actually need is the class `vdaisa_chap` and `vdaisa_req` because they will be identifiers as they're used as Sphinx directive names.
Am I overseeing something?

**Comment by danwos** [comment]
Creating a class for each word makes really no sense. The should be connected via "_" or "-".
We could also add the "directive" as class.

In my thoughts "directive" is mostly an abbreviation of "title", e.g. "req" and "requirement", "test" and "test case". Therefore "directive" was not taken as css-class.

I think we should only support one value to avoid confuses.
And I would like to still use "title", but connected with "_".

**Comment by ubmarco** [comment]
How can you make sure the title will be a valid CSS identifier? People can use any special characters there while the directive must be conforming to Sphinx identifiers which I consider safer.

**Comment by ubmarco** [comment]
Also using the title will implement logic the user has to know about (character replacement). So the user has to anticipate what needs will make out of the title to set it correctly in CSS. Using the directive would be more explicit.

**Comment by danwos** [comment]
Good points.
However, just now title is used and removing it would not be backwardcompatible. So it would break existing css styles.
Not a big drama, but not ideal.

**Comment by ubmarco** [comment]
Yes, backward compatibility is a thing. But when looking at above examples it seems the title is used but the implementation is buggy, so a breaking change is needed anyway.

If people used spaces in the title before, it did never work correctly. I guess migrating to directive-only and a note in the changelog would be ok for most users. Can needs detect if users go for the old style in their CSS, so a depreciation warning can be emitted?

**Comment by danwos** [comment]
Okay, need-type is now used instead of the longer, maybe whitespace containing type name.
Detection of used css is not possible.
