### ISSUE TITLE
needs_hide_options not working for link_incoming/outgoing

### ISSUE THREAD

**Issue by ubmarco** [useblocks/sphinxcontrib-needs#109]
I have the following configuration:
```
needs_hide_options = ['hidden', 'style', 'link_incoming', 'link_outgoing', 'test_field']

needs_extra_links = [
    {
        "option": "parent_chap",
        "incoming": "contains",
        "outgoing": "part of chapter",
        "copy": True,
    },
    {
        "option": "parent_req",
        "incoming": "sub-requirements",
        "outgoing": "part of requirement",
        "copy": True,
    },
]
```
The need directive
```
.. vdaisa_req::
    :id: VDAISA_REQ_01_02_07_01
    :req_level: should
    :parent_chap: VDAISA_CHAP_01_02
    :parent_req: VDAISA_REQ_01_02_07
    :style: [[gen_style_field()]]
    :test_field: True

    Es existiert ein Maßnahmenplan bzw. Statusübersicht der Maßnahmenumsetzung.
```
Renders to
![image](https://user-images.githubusercontent.com/839934/71516414-285d2b00-28a9-11ea-8c7c-95ba0d774198.png)
I don't want link_incoming and link_outgoing because I have defined more meaningful link names.
Is that a bug (or a feature)?

**Comment by danwos** [comment]
It's a bug and not an awesome feature :)
Will take a look on it in the next days.

**Comment by danwos** [comment]
Mhh looks like you have a bug in your configuration.
Please check with:
```
needs_hide_options = ['hidden', 'style', 'links_incoming', 'links_outgoing', 'test_field']
```
So link**s**_incoming instead of link_incomings. And same for link_outgoing.

**Comment by ubmarco** [comment]
Did you test that? It does not work for me, also with the changed names.
I can hide my own options, but not the predefined `links_incoming` and `links_outgoing`.
