### ISSUE TITLE
Feature request needs.json reading

### ISSUE THREAD

**Issue by ubmarco** [useblocks/sphinxcontrib-needs#11]
I have the usecase that several Sphinx projects are used to describe various parts of one software (we distinct between common parts & specific parts). All projects use the sphinxcontrib-needs extension. Now I want to be able to link needs in one project to needs in other projects.

**Implementation proposal**
The writing of needs.json was implemented in version 0.1.30.
This file could be made available for import into other projects. It would then be available in the Sphinx model and could be referenced like any other need. I'd use a new directive which I could add anywhere in the Sphinx project. I as user have to care about refreshing the needs.json file whenever a project gets updated. Ideally the directive would support not only local file locations but also HTTP URLs.

**Comment by danwos** [comment]
Great request.
I suggest a directive like **.. needimport::**

A usage incl. some options could look like:
``` 
.. needimport:: my_external_needs.json
   :version: 2
   :hide: false
   :filter: any filter rule (equal to needfilter directive)
```
Where:
* **version** specifies the needs of a specific version to import. Default: Last found version
* **hide**: specifies, if all imported needs shall get the hide-flag. Default: false
* **filter** specifies a filter, which imports matched needs only

The idea of supporting HTTP-locations is also very nice.
So a project could simply make its needs.json file public and other sphinx-projects don't have the need to copy this file to a local folder. Would make it much easier to keep things in sync.
