### ISSUE TITLE
Constraint checking

### ISSUE THREAD

**Issue by ubmarco** [useblocks/sphinxcontrib-needs#110]
This issue is a placeholder for discussions around constraint checking of needs and needs fields.
Currently I 'misuse' the `needs_functions` to achieve that:
```
needs_extra_links = [
    {
        "option": "parent_chap",
        "incoming": "contains",
        "outgoing": "part of chapter",
        "copy": True,
    },
    {
        "option": "parent_req",
        "incoming": "sub-requirements",
        "outgoing": "part of requirement",
        "copy": True,
    },
]

def gen_style_field(app, need, needs, *args, **kwargs):
    """
    :param app: sphinx app
    :param need: current need
    :param needs: dictionary of all needs. Key is the need id
    :return: str,int,float or list of elements of type str,int,float
    """
    indent_lvl = 0
    tmp_need = need
    while 'parent_req' in tmp_need:
        if not tmp_need['parent_req']:
            break
        cnt = len(tmp_need['parent_req'])
        if cnt != 1:
            raise Exception(f'parent_req of need {tmp_need["id"]} has {cnt} entries. Must be exactly 1.')
        indent_lvl += 1
        tmp_need = needs[tmp_need['parent_req'][0]]
    while 'parent_chap' in tmp_need:
        if not tmp_need['parent_chap']:
            break
        cnt = len(tmp_need['parent_chap'])
        if cnt != 1:
            raise Exception(f'parent_chap of need {tmp_need["id"]} has {cnt} entries. Must be exactly 1.')
        indent_lvl += 1
        tmp_need = needs[tmp_need['parent_chap'][0]]
    return "indent_lvl_" + str(indent_lvl)

needs_functions = [gen_style_field]
```
As a main feature, the code returns the nesting level of a need by evaluating the link structure for CSS highlighting in a hidden need field. As a side feature it also raises exceptions if several parents are given for a given custom defined link type.
I propose to add a feature to needs for common constraint checks on needs. I'm thinking of
* the title must follow a regex
* a field must always be given
* a field must not be empty / empty string
* a field must follow a given regex
* a field must be given for a specific need type (bigger topic, currently fields are availabe for all need types)
* a field must have a specific multiplicity (e.g. 1 for a single element, 2 for 2 elements)
* a field must match the same field of a linked need (user defines the link type to look for) if a link is given

More complex checks can also be performed using the `hidden` dynamic function or custom hidden functions named differently.

**Comment by danwos** [comment]
I think we can use the "filter-string" to define constraints.
If a filter returns true for a need, then a warning/error is raised.

```
needs_constraints = {
  'req_with_status': "type == 'req' and status is None or len(status) == 0",
  'valid_staatus' : "status not in ['open', 'closed']",
  ... 
}
```
These constraints are checked after all needs got read in and dync. functions got executed.
If a need raises a constraint, a sphinx-warning is printed.
One could use `-W` during sphinx-build to stop build with failure.

**Comment by ubmarco** [comment]
Good idea. Does this support more sophisticated checks which uses imports (like re)?

**Comment by danwos** [comment]
Filter strings already Support re.search().
Everything what is needed by user must be provided by us. So the user can not decide to use new filter functions by importing stuff.

However, if there is a good use case, we can support it.

**Comment by ubmarco** [comment]
I'm happy with the proposal for the new `needs_constraints` configuration variable.
What do the keys in the dictionary mean. Just for logging?

**Comment by danwos** [comment]
Yes just for logging and maybe someday also as reference, e.g. show needtable with findings of given constraint.

**Comment by danwos** [comment]
Done, see https://sphinxcontrib-needs.readthedocs.io/en/latest/configuration.html#needs-constraints

**Comment by ubmarco** [comment]
The configuration has been renamed to `needs_warnings` in b1c557c878de9eede08bf596826c731e019c3969.
The new documentation URL is https://sphinxcontrib-needs.readthedocs.io/en/latest/configuration.html#needs-warnings
