### ISSUE TITLE
Class structure for needs

### ISSUE THREAD

**Issue by ubmarco** [useblocks/sphinxcontrib-needs#111]
This issue shall serve as a placeholder for discussions around a UML-like class structure of need types and their fields.
I'm using needs to support and tailor the implementation of the information security management systems TISAX + ISO27001 in our company. This brings already huge value as I have all TISAX requirements defined as needs and can track the fulfillment of the standard on code level using Sphinx. This turns Git+Sphinx into a full blown documentation management / requirement management / risk management / asset management solution. Thanks for this.

In my scenario, I defined a UML class structure for the need items I want to describe using Plantuml.
Beyond others, it contains the classes `Asset`, `Control` and `Risk` with different properties:
```
class "Control\n(Action, Measure)" as control {
}

Class "Asset" as asset {
  -- One of the following types --
  $txt IT hardware
  $txt IT application
  $txt IT infrastructure
  $txt information electronic
  $txt information physical
  $txt persons keeping secrets
  $txt external services [e.g. cloud]
  --
  $person owner
  $enum protection category\n    [normal, high, very high]
  $enum life cycle status\n    [create, process, stored, deleted]
  $txt[] acceptable use policy
  $txt group\n    [infrastructure, workplace, int, ext]
  $txt usage approval
  $help handling support [tools, methods]
  $key encryption
}

Class "Risk" as risk {
  $txt owner
  $txt[] causes
  $txt[] impacts
  $enum probability [low, normal, high]
  $txt[] impacts_handling
  $txt[] acceptance_criteria
}
```
The only option in needs to model the class/field structure is to define a need directive for each class and define global fields using `needs_extra_options` that can theoretically be used on every need.  Also I can create link types using `needs_extra_links` to define meaningful link names.
The problem I have is that every field and link is global and I will probably have dozens of field names over the whole definition. I will quickly lose overview which field is allowed/required/constrained on which class.

I'm proposing to make extra options and link types specific to needs directives.
Together with the constraint checking in issue #110, this would be a killer feature for me.
I'd like to get your opinions on this.

**Comment by danwos** [comment]
Maybe #110 is already enough for this.

Just define a constraint, which defines not allowed usages of a field for a specific need-type. 
E.g. "type == 'risk' and encryption is not None or encryption != '' " .

I think the common case is that extra_options shall be available for all need-types.
So I would like to not complicate the extra_options registration process for this case.

If more is needed, then an extra configuration option / way shall be used.
In this case #110.

**Comment by ubmarco** [comment]
Thanks for the implementation proposal. That sounds like a solution.
Will this provide the option to hide fields per need-type because there is only one global option `needs_hide_options`. If fields are not set, they are never displayed, right?

**Comment by danwos** [comment]
Hidding values can be done by #102, so a specific layout is configured/used for a specific need type.
But it is not available yet....

**Comment by ubmarco** [comment]
The usage of [needs_warnings](https://sphinxcontrib-needs.readthedocs.io/en/latest/configuration.html#needs-warnings) to enforce a certain field structure is really neat. I will close the issue.
For any future reader, this is how I can use the same fields for multiple classes with different value constraints in my conf.py, in this case `category`. The two functions `warning_field_exist` and `warning_field_enum` are just helper functions. They make the code look tidy when enforcing a lot of field constraints.
```
needs_types = [
    {'directive': 'asset', 'title': 'Asset', 'prefix': 'ASSET', 'color': 'goldenrod', 'style': 'artifact'},
    {'directive': 'risk', 'title': 'Risk', 'prefix': 'RISK', 'color': 'red', 'style': 'artifact'},
]

needs_extra_options = {
    'category': directives.unchanged,
}

def warning_field_exist(need_type, field):
    """
    Helper function that returns a filter string returning all needs that does not have the specified field set.
    :param need_type: the need type
    :type need_type: str
    :param field: the needs fields that has to exist on the need_type
    :type field: str
    :return: needs filter string to be used in needs_warnings
    """
    return f"type == '{need_type}' and {field} is None"


def warning_field_enum(need_type, field, values):
    """
    Helper function that returns a filter string to be used in needs_warnings for enum fields.
    :param need_type: the need type
    :type need_type: str
    :param field: the needs fields
    :type field: str
    :param values: the allowed values
    :type values: List[str]
    :return: needs filter string to be used in needs_warnings
    """
    values_surrounded_by_quotes = [f"'{x}'" for x in values]
    return f"type == '{need_type}' and {field} not in [{', '.join(values_surrounded_by_quotes)}]"

needs_warnings = {
    'asset_category_unset': warning_field_exist('asset', 'category'),
    'asset_category_enum': warning_field_enum('asset', 'category', ['hardware', 'application', 'info_electronic',
                                                                    'info_phys', 'person_keeping_secrets',
                                                                    'ext_services']),
    'risk_category_enum': warning_field_enum('risk', 'category', ['normal', 'high', 'existential']),
}
```

**Comment by ubmarco** [comment]
Btw, my previous way of constraining fields to predefined enum values was
```
needs_extra_options = {
    'category': lambda argument: directives.choice(argument, ('hardware', 'application', 'normal', 'existential')),
}
```
This however does not support setting different enum values for different need types.
