### ISSUE TITLE
Warning for field/link misconfiguration

### ISSUE THREAD

**Issue by ubmarco** [useblocks/sphinxcontrib-needs#118]
I wrapped my head around a problem with this needs configuration (conf.py):
```
needs_types = [
    {'directive': 'asset', 'title': 'Asset', 'prefix': 'ASSET', 'color': 'goldenrod', 'style': 'artifact'},
    {'directive': 'risk', 'title': 'Risk', 'prefix': 'RISK', 'color': 'red', 'style': 'artifact'},
]
needs_extra_options = {
    'type': directives.unchanged,
}
needs_extra_links = [
    {
        "option": "affects",
        "incoming": "affected by",
        "outgoing": "affects",
        "copy": True,
    },
]
```
I want to manage risks and risks shall be of certain types. That's why I added the extra option `type`.
However setting the field never worked and the field never appeared in the rendered output.
I debugged a little and found out it's because the need has already a property called `type`, it stores the actual need type as given in `needs_types` dictionary.
So needs first accepts the extra option - I know that because I can set the field in RST - but then does not set it correctly. I see 2 options now:
1. Needs detects these problems and reports an error (warning would be not enough from my POV).
    This must also be done, if a user wants to define an extra option called `affects` because that's already used by the extra link in above example. And other needs internal field must also be excluded from both `needs_extra_options` and `needs_extra_links`.
2. Needs changes the implementation so that extra fields and links get a separate namespace. This is either possible by putting them into another dictionary, so they would be available via `need['fields']['type]` and `need['links']['affects']` or by using name mangling for the fields/links like Python does with the `__<name>__` class function names. Needs could mangle the names to e.g. `need[field__type]`.

I guess option 2 would mean a lot of changes in internals and documentation. But it would give users more freedom (they will like it).
Option 1 however is less effort and safe and makes the bug visible so other users don't run into this.

Thanks for help on this.

**Comment by ubmarco** [comment]
Just for the record, I circumvented the problem by renaming my `type` field to `category`. Everything works fine with that.

**Comment by danwos** [comment]
Decided to go with option 1: Check the configuration before starting the build.

I think option 2 would also not be possible, because an option and a link with the same name could not be configured in the needs-rst. There can only be one directive-option for each name.
