### ISSUE TITLE
Diagrams lacks items without links

### ISSUE THREAD

**Issue by ubmarco** [useblocks/sphinxcontrib-needs#13]
In my scenario I am maintaining user stories, specifications and test cases.
I use the following code to show a table and a diagram:

```
.. needfilter::
    :types: test
    :show_status:
    :show_tags:
    :sort_by: id
    :layout: table

.. needfilter::
    :types: story;spec;test
    :show_status:
    :show_tags:
    :layout: diagram
```

All test cases show up in the table. But in the diagram, one test case is missing. This test case does not have any no incoming or outgoing links (all others do).
This looks like a bug to me.

**Comment by danwos** [comment]
Close this, at it was reported for a (now) very old version.
In the meantime a lot of stuff was changed, so I'm pretty sure this bug is no valid anymore.
If I'm wrong, feel free to reopen.
