### ISSUE TITLE
Filter: needed_for() [tree  search]

### ISSUE THREAD

**Issue by AlbertMietus** [useblocks/sphinxcontrib-needs#130]
It would be great to have a filter (or better: selection option) to select *needs* that are needed for a *need*; so a direct link or an indirect one. 

Example: with 2 “product-needs”, P1 & P2; each having some requirements (some shared, some not), Rs-Rs7 & R1a-R1h & R2k-R2n; and each R having some Test, T* ..
I  should be able to generate/show a list of test for P1 only...

Thanks

**Comment by danwos** [comment]
Yeah, I also have this feature request in my projects.
Current solution for me is to use nested list comprehensions in filter-strings.
For you it could look like this untested!!):
```
[test for prod in needs if type=='product-needs' for req in prod['requirements'] for test in req['tests]]
```
But this a really ugly solution, as the lists in these filter_strings get recreated for each need everytime from scratch. So it can really kill the performance/build, if there are too many needs.

I'm already searching for a way to maybe cache these link-trees and make them reusable or to provide a function with a better performance. 
But I haven't done anything in this area in the past, so any help, opinions or hints are welcome.

**Comment by danwos** [comment]
Please see also #132.
This should give you full control for the search and is currently my preferred solution for your use case.

**Comment by danwos** [comment]
As the user-specific need-type and link configuration can be complex, I see no way to provide a simple solution/option here.
#132 makes such filters possible, so that I close this issue.
