### ISSUE TITLE
Python func for filtering (needtables and co)

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinxcontrib-needs#132]
The content area of needfilter and co shall be used for defining a user-defined function for the search.

This function must return a list of needs.
As argument only needs and app/env shall be provided.

If content is defined no other filter options are allowed (exception raised)

example:

```
.. needtable::
   :columns: id, title, status

   results = []
   for need in needs:
       if need['status]` == "open":
          for spec in need['spec_links']:
             if spec['status'] == 'open':
              results.append(need)
              continue

    return results
``` 
This functions gets executed only **once** per needtable.
Instead of a filter_string, which gets executed once per need.

So it should be much faster compared to filter_strings with list comprehensions (if the user does not define too fancy stuff).

**Comment by ubmarco** [comment]
I'd appreciate this feature, should bring a lot of flexibility to the user while avoiding confusing `filter_string`s for complex searches/filters.
