### ISSUE TITLE
needs_functions missing in configuration after upgrade to 0.5.5

### ISSUE THREAD

**Issue by vlotorev** [useblocks/sphinxcontrib-needs#147]
After upgrading from 0.5.4 to 0.5.5 build ends with an error:
```Sphinx error:
needs_functions missing in configuration.
make: *** [bring-up] Error 2
```
My `conf.py` related to needs extension:
```
# Sphinx needs settings
needs_role_need_template = "{id}"
needs_default_style = 'clean'
# Layout is based on https://github.com/useblocks/sphinxcontrib-needs/blob/master/sphinxcontrib/needs/defaults.py#L39
# Custom layout is only used to have collapse=False by default
needs_default_layout = 'simplified'
needs_layouts = {
    'simplified': {
        'grid': 'simple',
        'layout': {
            'head': [
                '<<meta_id()>>: **<<meta("title")>>** '
                '<<collapse_button("meta", collapsed="icon:arrow-down-circle", '
                    'visible="icon:arrow-right-circle", initial=True)>> '
            ],
            'meta': [
                '<<meta("type_name")>>',
                '<<meta_all(no_links=True)>>',
                '<<meta_links_all()>>'
            ],
        }
    }
}

needs_types = [
    dict(directive="req", title="Requirement", prefix="R", color="#BFD8D2", style="node"),
    dict(directive="spec", title="Specification", prefix="S", color="#FEDCD2", style="node"),
    dict(directive="impl", title="Implementation", prefix="I", color="#DF744A", style="node"),
    dict(directive="test", title="Test Case", prefix="T", color="#DCB239", style="node"),
]
needs_id_regex = r'^[A-Za-z0-9_:]{3,}'
```

**Comment by danwos** [comment]
Thanks for reporting,

I have some problems reproducing this error on my machine.
By I get the error, when I'm using the sphinx-test-reports extension, which uses an API call with some problems.
I fixed this API call in https://github.com/useblocks/sphinxcontrib-needs/commit/a8c442e442501e1d7f486d8392500e04f602ff10, but I'm not sure if this also fixes your problem.

Can you please checkout the latest commit and install it via ``pip install -e . `` on your local venv?
Then please rerun your build.

Thanks for your support.

**Comment by DigvijayPati** [comment]
I am also getting the same error with (`sphinxcontrib-needs 0.5.5` & `sphinx-test-reports 0.3.3`) . Version `0.5.4` works well though.

**Comment by danwos** [comment]
Okay I have released version 0.5.6, which should fix the bug.
Please check. Thanks!

**Comment by DigvijayPati** [comment]
`sphinxcontrib_needs-0.5.6` is working fine. Thank you very much.

**Comment by vlotorev** [comment]
Hi, sorry for delayed response.
Although I haven't mentioned it while filing an issue indeed I was using `sphinxcontrib-needs` with `sphinx-test-reports`.
I don't have time to check the issue is fixed. So lets close the ticket, as it was confirmed and checked by two persons except me.
Thanks for working on this project, `sphinx-collections` with Jinja is looking very promising.
