### ISSUE TITLE
Issues with single file requirements

### ISSUE THREAD

**Issue by danieleades** [useblocks/sphinxcontrib-needs#149]
I'm just getting started using this project to manage requirements/test cases.

I'm attempting to create a project that has one file per requirement (then the git log for that file captures the entire requirement history quite neatly).

I'm attempting to include multiple requirements under a single heading using the sphinx `include` directive, but `sphinxcontrib-needs` is complaining of duplicate requirement IDs. My best guess is that `sphinxcontrib-needs` is searching the tree for requirements irrespective of whether the documents are included in any TOC. So if i use the `include` directive i get two copies, and if i don't use it I have one copy of the requirement but it's not in the output. Does that make sense?

How can I structure my project so that I have one file per requirement (without having a separate heading for each requirement)?

**Comment by danieleades** [comment]
update: i've gotten this to work by changing the file extension on the single-file requirements to confound whatever search is taking place. Not ideal. 

Is there a better way?

**Comment by danwos** [comment]
This behavior is related to Sphinx itself.
Sphinx builds all rst/md files, whether they are included, referenced in toctree or something else.
It is enough to have somewhere a rst-file below your ``conf.py`` and it get built.

However, you can use the exclude_pattern: https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-exclude_patterns

So putting everything in a single folder, add it to exclude_pattern and then include wherever it is needed should work.
Or have a prefix for all of your requirement-files, like `req_123.rst` and use this in the pattern.

**Comment by danieleades** [comment]
Thanks for the quick response! That gets me out of trouble

**Comment by danieleades** [comment]
the way i solved this was by *not* excluding the files, but suppressing the "not included in any TOC" warnings by putting `:orphan:` directives at the top of each file, and then generating a list of the requirements using a `needextract`
