### ISSUE TITLE
sorting on extra options

### ISSUE THREAD

**Issue by danieleades** [useblocks/sphinxcontrib-needs#150]
I have an extra option on my needs called 'priority', and i'm attempting to sort a needextract with

.. needextract::
    :sort_by: priority
    :status: open
and i'm getting WARNING: Sorting parameter priority not valid: Error: 'priority'

i'm also getting the same error if i change from `needextract` to `needlist`

**Comment by danieleades** [comment]
i'm also getting errors attempting to filter on priority-

```rst
.. needextract::
    :types: Requirement
    :filter: priority == 0
```

`sphinxcontrib.needs.filter_common.NeedInvalidFilter: Filter priority == 0 not valid: Error: name 'priority' is not defined`

**Comment by danieleades** [comment]
this is now working.

I updated all my dependencies and cleared the build cache. I'm *guessing* clearing the build cache is what resolved the problem.

closing

**Comment by danwos** [comment]
Yes, the build cache is often the reason for trouble.
Especially when sphinx-needs related configuration was changed.
Then the cache stores the internal need-dictionary with the old conf and sphinx-needs often fails validating the old-data with the new config.
