### ISSUE TITLE
Migrate to Poetry

### ISSUE THREAD

**Issue by danieleades** [useblocks/sphinxcontrib-needs#153]
I wanted to use this ticket to explore the problem space around migrating to [Poetry](https://python-poetry.org/) for package management.

One of the issues flagged in #152 is that installation with Pip must be possible for backwards compatibility. This can be achieved through Poetry's [export](https://python-poetry.org/docs/cli/#export) command, which allows exporting a `requirements.txt` file.
Poetry does not (at the time of writing) provide a mechanism for automatically keeping the `requirements.txt` file in sync with `pyproject.toml` and `poetry.lock`. This must be done with a script and/or a CI check.

Other than that, I think Poetry can simplify the development experience, and also act as a script runner.

**Comment by danwos** [comment]
After a talk to another contributor: Supporting ``pip`` and ``poetry`` seems not to be necessary.
So changing everything to poetry would be fine for me.
