### ISSUE TITLE
Please add a LICENSE

### ISSUE THREAD

**Issue by avyfain** [useblocks/sphinxcontrib-needs#16]
Hello, I found your project on https://github.com/yoloseem/awesome-sphinxdoc, and it seems like a useful tool that I'd like to use. Without an explicit license file on your repo I can't add this to my projects.

Could you please add a LICENSE file? Here are some useful resources you can consider to pick the right license for your project:

* [GitHub's guide](https://help.github.com/articles/adding-a-license-to-a-repository/)
* [choosealicense.com](https://choosealicense.com/)

**Comment by danwos** [comment]
Oh my god, I really forgot this (it's MIT license).
Thanks for the hint and the helpful links.

I will also raise the version and make a release on pypi (after implementing 1-2 more features, which should happen in the next hours).

**Comment by avyfain** [comment]
Awesome! Thanks for building this, and for publishing your code under the MIT license :)
