### ISSUE TITLE
The role :need_outgoing: does not seem to be working

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#160]
The role `:need_outgoing:` does not create any outgoing links. 

See example provided which shows this issue as well:
https://sphinxcontrib-needs.readthedocs.io/en/latest/roles.html#need-outgoing
>**Result**: To get butter on our bread, we need to fulfill **_None_**

**Comment by danwos** [comment]
Thanks for reporting the bug.
As it affects an already implemented and often used feature, I have already worked on a small bugfix.

**Comment by danwos** [comment]
Working now again. 
Not sure when I will create the release for it...

![image](https://user-images.githubusercontent.com/998700/99375222-c3952f80-28c3-11eb-82be-5dcb723cc9bf.png)
