### ISSUE TITLE
needtable is invisible on wide viewports when using 'read the docs' theme

### ISSUE THREAD

**Issue by danieleades** [useblocks/sphinxcontrib-needs#164]
what is says on the tin.

see https://github.com/useblocks/sphinxcontrib-needs/issues/77#issuecomment-750057106

**Comment by danieleades** [comment]
i've created a minimal reproduction of this issue - https://github.com/danieleades/sphinx-needs-issue-164

**Comment by danieleades** [comment]
looks like there's a bit of bespoke css and javascript specifically for handling reactivity of tables when using the read_the_docs theme. I'm guessing this needs to be revisited? Looks like black magic to me

**Comment by twodrops** [comment]
@danwos We are also using rtd as needtables is not usable with this theme
![2021-05-01_06h32_32](https://user-images.githubusercontent.com/103930/116770917-8377d280-aa47-11eb-82f9-e5e70f6d115b.png)

**Comment by danieleades** [comment]
i've updated my reproduction to the latest package versions. the behaviour has changed *slightly*. Instead of being totally invisible, the table now matches @twodrops' screenshot above. It's still unusable.

**Comment by danieleades** [comment]
hey @danwos have you come across [issuehunt](https://issuehunt.io/)? Could start putting bounties on some of these issues...

**Comment by danwos** [comment]
Thanks for updating the issue.
Yes, the RTD theme makes some not so nice assumptions, e.g. ALL tables must get modified by their theme.
I will try to fix it in the next days.

But it could change with each new RTD-theme version, so I'm not sure how long a fix would work.

I think I should create an issue on RTD to ask for some ideas how to deal with tables coming from and managed by sphinx extensions.

@danieleades: **issuehunt** looks promising, but I have no experiences with it.
Can everybody put a bounty on an issue?
Or must this be done by the project admins?
However, I started a general discussion for it: #261 (draft status) .
Maybe there are other services/ideas as well.
But overall, good idea :+1:

**Comment by danwos** [comment]
Fixed it, somehow.
I'm not so happy with the solution, as I need to deactivate "overflow" for all tables. Not only Sphinx-Needs tables.

```
div.wy-table-responsive {
    overflow: unset;
}
```

Another solution would be to change the css attributes with the help of Javascript.
In this case I can make sure to modify ``div.wy-table-responsive`` only on `´divs``, which have a Sphinx-Needs table as child.

So can someone check this PR with his/her project and set up?
Do all tables look good? Are they still responsive?

**Comment by danieleades** [comment]
I can confirm that this fixes my minimal reproduction.

did you end up making an upstream issue in the end?

**Comment by danwos** [comment]
No, as I'm not sure how this dilemma could be fixed.
Maybe the RTD thme could be configured by user to deactivate its css-settings for tables.
But then users need to configure something and I want to avoid this.
So at the end, best solution would be if Sphinx-Needs can provide the needed css-configs.
But this only works as long as this part stays somehow stable in the RTD theme.
