### ISSUE TITLE
LICENSE file not included in PyPI tarball

### ISSUE THREAD

**Issue by Cilyan** [useblocks/sphinxcontrib-needs#165]
Minor issue: the LICENSE file is not included in the MANIFEST.in, and as such is not included in the tarball submitted to PyPI. As the license is MIT, the license file must be included to package for some distributions, and so at the moment the workaround is to also download the LICENSE file from the github repository, which is not completely reliable (possibility of a mismatch in case of license change).

Suggestion: add `include LICENSE` to MANIFEST.in.

**Comment by danwos** [comment]
Thanks for reporting and already fixed.
The next release may need so time as I just have released 0.6.0.
But I guess there will be some bugfixes in the next days, so that a new release makes sense.
