### ISSUE TITLE
need_part and plantUML:usecase fails (some plantuml "types" do not nest)

### ISSUE THREAD

**Issue by AlbertMietus** [useblocks/sphinxcontrib-needs#170]
When a *need* has  **need_parts**, **AND** that need-type is configured as (by example)  `style=="usecase"`  (by setting _need_types_), plantUML will not generate a diagram. It will simply fail

After some investigation:

* Needs generate a plantUML file as :
   >   ' Nodes definition  
   >   ...
   >  $STYLE ... {
   >    rectangle  "the sub/part need ..."
   >   ...
  > }
* Some plantuml "types" can be nested, other not
   - frame/frame is Oke
   - package/package is Oke
   -  usecase/usecase is **NOT OK**
   - actor/actor is **NOT OK**
    - *Not all combies are is tried*
* So, when  one configures to use an oval/usecase "type" |[correct & allowed]|, AND uses sub-needs (`:np:`)  [[Allowed & correct]|, and insert a `need_flow` directive ==> sphinx will fail, only giving a trivial error, on a page that isn't changed .....
 
I solved it by drawing usecase as packages. I guess an nested ovals is possible; but plant doesn't . So maybe it's a plantUML flaw (although is is not documented that is is allowed) .

Plz document (at least).

Or better: check on such combines and signal a warning in needs that plant may not support it. As the current behaviour is hard to understand

Thanks

**Comment by danwos** [comment]
Thanks for reporting.
Yes that's really a small but annoying problem.

I have updated the docs and set a warning in the section for setting up custom need_types.

As this problem is based on PlantUML and may be implemented deferentially for different PlantUML versions as well, I see no way to catch this safely in our code without testing it again for each new PlantUML version.
So no code changes here, sorry. Docs must be enough.

**Comment by AlbertMietus** [comment]
There is a fix possible, IMHO;  by reversing nested -draw-style. Let me explain ...

Assume there is a need  **N1** with type _T1_, configured to be drawn as (plantUML) style `S1`, And a need  **N2**, type: _T2_ and drawns as `S2`. This work: we will see the (non nested) element `S1` ... `S2`
Suppose the is also a need **N3** (_T3_, `S3`) with parts: **N3a** and **N3b**.

_Currently_ this will be drawn a a `S3`-element with 2 rectangles, inside for **N3a** & **N3b**. The rectables are hard-coded (neeflow.py::process_needflow(), around line 227
This only works (in plantUML)  when S3 can act as a package; so can have things inside. Which is not always the case.

My proposal is to draw the parts a the configed style, and the rectangle around it for the need itself
Then we will see `S1`, `S2 `(as before), two `S3` elements for **N3a** & N3B, and rectangle around the two `S3`s , **N3**.  Plant can draw that, ALWAYS as rectangles can have "parts" inside.

Probably, using a package instead of the rectangle is even better. Of make in configurable. 

And, thinking about it, using the Style for the parts and a rectangle/package around is (IMHI) even better. The part kind-of inherites the type; it ain't a "rectangle".
