### ISSUE TITLE
'test_build_epub' hangs indefinitely

### ISSUE THREAD

**Issue by danieleades** [useblocks/sphinxcontrib-needs#177]
when i run the tests, `test_build_epub` hangs indefinitely.

Are there perhaps extra packages required to run this test which are not listed in the `test-requirements.txt`, or something along these lines?

or is it just me?

**Comment by danwos** [comment]
This test was never a problem on my machine or on travis ci (for no python / sphinx version combination).
So not sure what's not working.

But I just retested it and the pub-test takes long (52s) but finally delivers.
Mhh but also the test_build_html took really long, which creates the sphinx-needs docs only.
Creating this "by hand" via ``make html`` took not so long....
Not sure if the reason for this is also the reason for your problem.
Need to take a deeper look....

**Comment by danieleades** [comment]
it's really hard to tell me for. Because I couldn't run the tests before, and i've tried to migrate to Nox+Poetry, it's impossible for me to tell what was already broken, what I broke, and what is the result of differences in my build environment!

**Comment by danwos** [comment]
Do you set up your test-environment by using tox.
Or by creating your own virtual env?

Normally I just do on a fresh system:
```
pip install -r test-requirements.txt
tox
# or tox -e env-name to start test for certain version-combination only
```

As tests are working on CI and my system, I will close this issue in the next days.
For now I keep it open to maybe discuss what goes wrong on your machine.

**Comment by danieleades** [comment]
yeah i think this can be closed
