### ISSUE TITLE
possible logic bug in `layout.py`

### ISSUE THREAD

**Issue by danieleades** [useblocks/sphinxcontrib-needs#181]
possible logic bug in `layout.py`

https://github.com/useblocks/sphinxcontrib-needs/blob/a7df6d096611dc68092cbe6dc66ce7cbb75b83e6/sphinxcontrib/needs/layout.py#L592

i'm pretty sure this isn't doing what it's supposed to do

```python
if not show_empty and result is None or len(str(result)) == 0 or bool(result) is False:
    continue
```

by operator precendence, is equivalent to

```python
if (not show_empty and result is None) or len(str(result)) == 0 or bool(result) is False:
    continue
```

which doesn't really make any sense.

Is this perhaps what this is *trying* to check? - 

```python
if not show_empty and not result:
    continue
```

or, equivalently - 

```python
if not (show_empty or result):
    continue
```

(by De Morgan's laws)

**Comment by danwos** [comment]
Yes, I agree.
Looks like some fancy/wrong logic, which I thought it was needed to support python2.7.
So it can be simplified :)
