### ISSUE TITLE
:sort: on ID in tables with a :np: looks wrong

### ISSUE THREAD

**Issue by AlbertMietus** [useblocks/sphinxcontrib-needs#185]
When sorting a ``.. needtable``, the table is often not fully sorted: the need_part are inserted at random (or something)

Currently, I writing requirements with parts (``:np:``) and like to list them in a table. Which is sorted on ID (using `` :sort: id``).
Then, the table is mostly sorted, but not fully. When I neglects the row with a :need_part:, it seems fine. But those ``:np:`` lines look like randomly inserted. The are not even sorted on the _arrow prefix_!

I expected to see those parts to show just below the main need, again sorted on the ID itself

Note: the :show_parts: option doesn't have any effect I see those parts anyhow.  So maybe the flaw is in that functionality 

I'm (was) using _sphinxcontrib_needs-0.5.6_. And trying **0.6.0** now ... Same: not sorted, always shown
Running on Windows (sorry:-); using (ana)conda

**Comment by AlbertMietus** [comment]
The fix, to sort on ID, looks simple: 1 line

Instead of sorting on the `'id'` attr -- which only contains the "np id"--, sort on `'id_complete'`. The one has the *real/main* ID already prefixed.

See the fix below, in needtable.py line 171 (rel=0.6.0), marked with GAM

```python
...
        def get_sorter(key):
            """
            Returns a sort-function for a given need-key.
            :param key: key of need object as string
            :return:  function to use in sort(key=x)
            """
            if key == 'id': key='id_complete'                           # GAM
            
            def sort(need):
...
```

Probably a a bit more work is needed for a nice fit. However, this one works

Note: ``key=key.lower()`` would be a nice add-on. As at least I often mistakenly use capitals when specifying the sort-field `:sort: ID` vs `:sort: id` -- I know, it is wrong ....

**Comment by AlbertMietus** [comment]
The `:show_parts:` field looks like unrelated. 

However, I expected not specifying it would skip a need_part rows. It doesn't  And specifying it show it twice. Is this the intention? (I do't see the use-case)
Assuming it is a I expect, there is another bug ... Hope to provide a fix later

**Comment by AlbertMietus** [comment]
A fix for `:show_parts:` (As described above)

Again, it looks simple. Add 2 lines and remove 28 ... (in *process_needtables*)

In needtable.py line line 191 the big loop  can be skipped for parts. By adding 2 lines (marked by GAM)

````python
...
        for need_info in found_needs:
            if True and not current_needtable["show_parts"] and need_info['is_part']:  # GAM
                continue                                                                                                          # GAM
...
````
Note: the if `True and` is only to mark the addition

And remove 28 lines around line 230
````python
...
            # Need part rows
            if False and current_needtable["show_parts"] and need_info['is_need']:  # GAM: skip this part (28 lines)
...
````
Again the ``False and`` is only to mark that if-body can be deleted

Hope it helps

**Comment by danwos** [comment]
Not sure if the ``:show_parts:`` thing is really a bug.
The showed needs depend on your filter.
``show_parts`` makes sense, when your search only filters for needs (and no need_part).
To show all the need_parts of the filtered needs, ``show_parts`` can be used.

This may be needed, as the used filter-rules for needs may not match the underlying need_parts.

Therefore also your observation of getting need_parts twice in the result list makes sense, as the filter covers both (needs and part) and then additionally ``show_parts`` loads the need_parts of the found needs another time.

In most cases I would use ``show_parts`` together with filter part ``is_part is False``, to be sure to have no need_parts in filter result.

**Comment by danwos** [comment]
I switched the default sort to ``id_complete``.
So ``id`` can still be set for ``:sort:`` without getting overwritten.

I'm haven't added any lower/uppercase transformation, as think that options fields can be configured to be case sensitive.
But I'm not sure and have to recheck the code, if options get always internally transformed to lowercase.

**Comment by AlbertMietus** [comment]
> I'm haven't added any lower/uppercase transformation, as think that options fields can be configured to be case sensitive.

I typical use ``:ID:`` (capitals) to set the id. It works;  so it is case-insensitive there. Also, I have seen many `.lowercase()` call in the code. And, it sounds like a sound practice.

Q: Is `id_complete` valid as sort argument? Ik like to be explicit (one and a while:-)

**Comment by AlbertMietus** [comment]
> Not sure if the `:show_parts:` thing is really a bug.

I would expect, when using a needtable, the default behaviour is sound. Currently is "looking wrong".
Possible, when using filters it the current use is valid. But the default behavior is a bug (IMHO). It adds the same line twice. 

Possible, we can add a value to give the user/writer the freedom (s)he need: No parts at all, parts added once, or twice -- I don't see the use of this, but OK

By example:
* `:show_parts: None`, `:show_parts: False`
    No parts are shown
* `:show_parts: always`  `:show_parts: True`
    Add each part once
* `:show_parts: filter` ,  `:show_parts:` 
   The parts are input for the filter, and are shown depending on that filer.
