### ISSUE TITLE
unexpected warning on services when upgrading to 0.6

### ISSUE THREAD

**Issue by AlbertMietus** [useblocks/sphinxcontrib-needs#186]
needs-0.6 introduced **services**, which are not available before.  So, when upgrading you don't had them configured).  Or possible you don't need that feature.

Still, you _(everybody will)_ get 3 warnings on them:
```
WARNING: No service config found for github-issues. Add it in your conf.py to needs_services dictionary.
WARNING: No service config found for github-prs. Add it in your conf.py to needs_services dictionary.
WARNING: No service config found for github-commits. Add it in your conf.py to needs_services dictionary.
```

Two remarks:
1.  I can't find documentation to disable this feature. And to get the warning "away"
2.  It would be better to have a default without this feature/ warning, when using the "old" config

And 2 request: 
* Can the docs mention this, warn for it and provide the solution (disable in conf.py)  
   This is probably easy; as it is online
*  Make a fix for it (0.6a or something) so that users don't get bothered :-)
    As 06 is out, is not that easy to do it painless

**Comment by danwos** [comment]
Thanks for the report.
I'm already aware of this annoying warning, but haven't found the time to fix it.
But I totally agree, there should be no warning for default configuration.
So the warning gets removed with next release.

**Comment by twodrops** [comment]
I was about to report it and found this issue. Glad that it is a known issue planned to be fixed

**Comment by danwos** [comment]
Closed already with #168.
Only release is missing, but I'm working on it...

**Comment by twodrops** [comment]
Thanks a lot. Btw, I love the new needservice. It opens the doors for many other things.
Had a minor issue with a missing "/" at the end of url in the config file. I raised PR #188 .

**Comment by AlbertMietus** [comment]
Does this also solve the annoying 3 "extra" items in every (needflow) legend?

The are apparently added with a lines as:
```  add_need_type(self.app, 'pr', 'PullRequest', 'PR_', '#aaaaaa', 'card')```
In the GH-service class' `__init__()`. But can't figure-out where/when it is called 

For professional _non-opensource_ use-cases, it looks scary ;-) 

Note: was not able to test, but hope it will be in 061
