### ISSUE TITLE
Needs directive inside Doxygen throws an exception

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#193]
I was trying to use Needs directive within Doxygen comments of a C++ file. Any Sphinx directive works fine but not the Needs ones.

- I am using the "breathe" extension

- Added the following to Doxygen file
```
ALIASES  = "rst=\verbatim embed:rst:leading-asterisk"
ALIASES += "endrst=\endverbatim"
```

- The following works fine:
 ```
/**
    @brief This is used by any class extending to pre-define a set of histograms to book by default.
    @rst
       .. note:: Some note.
    @endrst
   **/
class MyClass
```

- The following throws an exception:
 ```
/**
    @brief This is used by any class extending to pre-define a set of histograms to book by default.
    @rst
        .. need:: User needs to login
          :id: ID123
          :status: open
          :tags: user;login
          :collapse: false
    @endrst
 */
class MyClass
```
Throws:
```
Extension error:
Handler <function process_need_nodes at 0x7f45049b7ca0> for event 'doctree-resolved' threw an exception (exception: list index out of range)
```

**Comment by twodrops** [comment]
### How to reproduce

1. Use attached [doxygen_example.zip](https://github.com/useblocks/sphinxcontrib-needs/files/6315106/doxygen_example.zip) (adapt conf.py if needed)
2. Install breathe and doxygen
   ``` bash
   pip install breathe
   apt install doxygen
   ```
3. Run
   ``` bash
   make html
   ```

**Comment by danwos** [comment]
Thanks for the helpful example.
Bug is fixed and result looks good:
![image](https://user-images.githubusercontent.com/998700/114922231-ba38d080-9e2b-11eb-8b22-51b027908b9c.png)

**Comment by twodrops** [comment]
Thanks a lot for the quickkkkkk fix 👍🏽 
It works as expected for me and I can now create needs within doxygen. Great!!

I observed 3 new issues.

1. I can create a link from a ``need`` defined within doxygen to a different ``need`` (outgoing). However the link on the target ''need'' is not created (incoming). Strangely enough the incoming link is visible in a ``needtable``.
If I copy the same ``need`` from doxygen to rst, both links are visible directly on the need.

2. For one of the custom need type I have, when used from doxygen threw this error. The same need block copied to rst worked fine. I can create an example for this if you wish.
```
Extension error (sphinxcontrib.needs.directives.needflow):
Handler <function process_needflow at 0x7f3e3c92c5e0> for event 'doctree-resolved' threw an exception (exception: 'refid')
make: *** [Makefile:29: html] Fehler 2
```
3. This might be unrelated and I can open a new issue if you want.
A ``:need:`` role within doxygen throws the following exception. This time from Breathe however.
```
Exception occurred:
  File "/usr/local/lib/python3.9/site-packages/docutils-0.16-py3.9.egg/docutils/nodes.py", line 2018, in unknown_visit
    raise NotImplementedError(
NotImplementedError: <class 'breathe.renderer.sphinxrenderer.NodeFinder'> visiting unknown node type: NeedRef
```

**Comment by danwos** [comment]
Thanks for reporting the new findings.
I created 3 new issues for them: #229, #230, #231
