### ISSUE TITLE
GitHub services returns maximum five contents

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#199]
I observed that GitHub services returns by default a max_amount of 5 (tested with github-issues). To get all contents, I had to set max_amount to -1. Is this the expected behavior?

**Comment by danwos** [comment]
Yes right, it defined like this of no value is set:
``self.max_amount = self.config.get('max_amount', 5)``

But I agree that this makes no sense, will change it to -1 to get all content

**Comment by danwos** [comment]
Just noticed that max_amount defines the amount of data which gets back for the first page.
And only the first page gets loaded.
I think there is a maximum of 500 for elements per page (coming from github api itself).
So currently need service can fetch a maximum of 500 elements.
Do you think that constraint is okay for your use case?

Personally I don't see any use case, where a huge list of >500 elements on a single documentation page is helpful.
So I would no change this "max 500" constraint.
