### ISSUE TITLE
New feature:  Restrict tags

### ISSUE THREAD

**Issue by ubmarco** [useblocks/sphinxcontrib-needs#2]
**Feature request**
As a user I want to restrict the values that may occur for the 'tags' field so that I can introduce standards for my Sphinx projects.

**Implementation proposal**
New configuration dictionary in conf.py:
```
needs_tags_whitelist = {
  '<tag_1>': "<tag_1_description>",
  '<tag_2>': "<tag_2_description>"
}
```

**Comment by ubmarco** [comment]
**New implementation proposal**
- conf.py
  New boolean flag `needs_defined_tags_only`
- any .rst file
  New directive 'needs_tag' which defines a tag and outputs nothing
  Fields
  ```
  .. needs_tag::
      :name: ui
      :description: User Interface
  ```
- any .rst file
  New directive 'needs_legend_tags' which dumps a legend for all tags.

**Comment by danwos** [comment]
Implemented initial proposal only.
