### ISSUE TITLE
Informative error message needed for nonexistant needs 

### ISSUE THREAD

**Issue by danielvasas** [useblocks/sphinxcontrib-needs#20]
In case a non-existant need is referenced, an exception is thrown back at the user:

Exception occurred:
  File "c:\dev\ve_safe_build_36\lib\site-packages\sphinx\environment\__init__.py", line 308, in warn_node
    self._warnfunc(msg, '%s:%s' % get_source_line(node), **kwargs)
TypeError: 'NoneType' object is not callable
The full traceback has been saved in C:\Users\qxq6176\AppData\Local\Temp\sphinx-err-d4a3tnss.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

An error message would be very helpful in this case.

**Comment by danwos** [comment]
Solved by #24.
Part of version 0.1.48
