### ISSUE TITLE
need_part returns 404 within needflow

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#205]
need_part when clicked in needflow (as SVG) returns 404

**Comment by danwos** [comment]
### Analysis:
Taking this image from official docs:
https://sphinxcontrib-needs.readthedocs.io/en/latest/_images/plantuml-8cbdbf2b0245d02ce4e68e9caef1315c50246f48.svg
[source-page](https://sphinxcontrib-needs.readthedocs.io/en/latest/directives/needflow.html#link-types)

Need-parts svg elements get links like:
https://sphinxcontrib-needs.readthedocs.io/en/latest/_images/.._directives_needflow.html_spec_flow_001

Normal needs get links like:
https://sphinxcontrib-needs.readthedocs.io/en/latest/directives/needflow.html#spec_flow_001

So the need-part url is completely broken:
* ``_images/.._directives_`` should not be part of it
* need_part id is missing, like ``#spec_flow_001.subspec_1``
