### ISSUE TITLE
needs_warnings example throws an error

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#209]
The [needs_warnings example](https://sphinxcontrib-needs.readthedocs.io/en/latest/configuration.html#needs-warnings) below throws an error.
`'req_with_no_status': "type == 'req' and status is None or len(status) == 0"`

```
sphinxcontrib.needs.filter_common.NeedInvalidFilter: Filter type == 'req-sw' and status is None or len(status) == 0 not valid: Error: object of type 'NoneType' has no len()
```

The example works when changed to 
`'req_with_no_status': "type == 'req' and (status is None or len(status) == 0)"`

**Comment by danieleades** [comment]
this should probably be

`'req_with_no_status': "type == 'req' and not status"`
