### ISSUE TITLE
Dockerized setup

### ISSUE THREAD

**Issue by tlwt** [useblocks/sphinxcontrib-needs#22]
Great approach for requirements management. I started dockerizing it at https://github.com/tlwt/sphinxneeds-docker.

Feel free to integrate it into your repository either as an automated build.

**Comment by danwos** [comment]
Awesome! :+1: 
Will try to add a link in our documentation.

**Comment by danwos** [comment]
I hope you are fine with this kind of integration:
http://sphinxcontrib-needs.readthedocs.io/en/latest/installation.html#using-docker

And thanks again for all the work you haven spent for sphinx-needs!
