### ISSUE TITLE
needimport ignores all links between needs

### ISSUE THREAD

**Issue by arnoox** [useblocks/sphinxcontrib-needs#227]
I have a proper `needs.json` containing some valid needs that are linked to each other. Now when I "needimport" this file, all needs are imported, but without links. I couldn't find a hint in the documentation, that specifies this behavior: https://sphinxcontrib-needs.readthedocs.io/en/latest/directives/needimport.html

Probably this is a bug? Or are there any other way to achieve this?

**Comment by arnoox** [comment]
**Hint**: I could reproduce this with version `sphinx-build 3.5.3`.

**Comment by danwos** [comment]
Thanks for sharing this bug report.

I can reproduce the bug for extra_links.
So links via ``:links:`` options are working for me.
They get exported to ``needs.json`` and imported back.
@arnoox: Can you confirm this?

Only for additional links (configured via [needs_extra_links](https://sphinxcontrib-needs.readthedocs.io/en/latest/configuration.html#needs-extra-links)) I get this problem.

They are **not** exported to ``needs.json``.
I changed the ``needs.json`` by hand to get the links into it.
But also ``need_import`` ignores them.

So I see two bugs here, both related to ``needs_extra_links``:
- Needs-builder does not export them
- and ``need_Import`` does not import them.

**Comment by arnoox** [comment]
I can confirm that everything is working fine for regular `:links:`. They get properly exported; they also are properly imported.

In my case, the *needs_extra_links*:
- seem to be exported properly using `sphinx-build -b needs docs/ build/`
- are not imported at all using `.. needimport:: path/to/needs.json`

**Comment by arnoox** [comment]
Thanks for fixing!

I wanted to test this by locally installing sphinxcontrib-needs, but I failed because setup.py was apparently deprecated: so the following install steps from the README don't work anymore: `python setup.py install`

@danwos : could you please provide the updated install steps?

**Comment by twodrops** [comment]
@arnoox The new instructions to build from sources are here https://github.com/useblocks/sphinxcontrib-needs/blob/master/docs/contributing.rst

I guess the Readme update was missed during the Poetry migration.

@danwos  Do you want to point to `contributing.rst` from Readme?

**Comment by danwos** [comment]
Thanks for the hint :+1: and I have updated the docs.
I think you can use ``pip install -e .`` to install from source.

**Comment by twodrops** [comment]
@danwos @arnoox 
`pip install -e .` does not seem to work without a setup.py. I created a new issue here #241
