### ISSUE TITLE
process_need_ref:: env._warnfunc may/will crash

### ISSUE THREAD

**Issue by AlbertMietus** [useblocks/sphinxcontrib-needs#24]
When a need (-ref) is not found, Sphinx-doc does crash: It calls ``env.warn_node()``, which will call ``self._warnfunc``, which is ``None``. So, the warning results in a **dump**!

In file `sphinx/environment/__init__.py`, the function  ``BuildEnvironment.set_warnfunc()`` mentions 

> " ... is now  deprecated. Use sphinx.util.logging instead." (RemovedInSphinx20Warning)

FIX
===

With a few lines, this crash can be fixed. Although the output is possible to a the author intends - it does the trick however. And mentions the missing ref, without crashing. And with resulting in a resulting doc.

add (top-of-file)
-----------------

```
from sphinx.util import logging
log = logging.getLogger(__name__)
```

Replace:
---------

The line with ``env.warn_node()`` with:
```
 log.warning('Needs: need %s not found' % node_need_ref['reftarget'], node_need_ref)
```

**Comment by danwos** [comment]
Thanks for the detailed bug report and also for diving so deep into the code to provide a working solution.
Fix will be available with upcoming release.
