### ISSUE TITLE
Installation from sources does not work after Poetry migration

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#241]
Installation from sources with the following does not work after #216 implementation.

```bash
pip install -e .
```

It fails with the error:

`ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: xxxxx
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.`

There are some solutions/workarounds mentioned here, but did not find anything straight-forward
https://github.com/python-poetry/poetry/issues/1279
https://github.com/python-poetry/poetry/issues/34

**Comment by danwos** [comment]
Yes, have not tested it. My shame....

Another idea: you can leave away the -e option.
In this case you have to call 'pip install .' everytime a change in the directory is made (e g. by git pull).

Am 22. April 2021 06:55:13 MESZ schrieb Nirmal Sasidharan ***@***.***>:

**Comment by twodrops** [comment]
@danwos Thanks for the tip. It works!

**Comment by danwos** [comment]
Updated docs and close this ticket.

**Comment by twodrops** [comment]
@danwos The readme and docs/installation.rst still says
```bash
pip install -e .
```
does it mean this works now instead of 
```bash
pip install .
```

**Comment by danwos** [comment]
PR for this is on the way :)
So still ``pip install .``, no ``-e``
