### ISSUE TITLE
Nested needs

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinxcontrib-needs#249]
The content area of a need can contain another need.

Right now a need does not know, if it is part of another need or stores other needs on its content.
This shall be collected, like signatures and sections are collected.

## Spec
* A new variable ``parent_need`` for ``need_info`` which stores the direct parent of a need
* A new variable ``parent_needs`` for ``need_info`` which stores a list of **all** parents (so from each level)

**Comment by twodrops** [comment]
@danwos 
A small thing I noticed is that if there is a build folder generated with an older version (say 0.6.1), the fix throws the following exception:
>Extension error (sphinxcontrib.needs.directives.need):
Handler <function process_need_nodes at 0x7febd4f9fb80> for event 'doctree-resolved' threw an exception (exception: 'backlink_creation_parent_needs')

If the build folder is cleared and generated, everything works as before.
Is this a problem?

**Comment by danwos** [comment]
That's a normal behavior, as Sphinx caches need objects internally and reuses them.
But if an update added new data and access this, the cache gets not updated.
So new code tries to work with "old" need objects,
If this throws an exception, depends on the introduced functions.

So cleaning the build folder is the only way to solve this.
