### ISSUE TITLE
js/css files copy not working if cwd not correct

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinxcontrib-needs#252]
This will not work, if cwd is not sphinx_conf folder.
```static_data_file = Path("_static") / filename```

Use ``app.confdir`` or similar to make the path absolute,

**Comment by danwos** [comment]
@twodrops: Found the bug and have tested the fix locally, on rtd and inside docker. 
Looks good for me. Can you please confirm.

**Comment by twodrops** [comment]
@danwos Thanks a lot for the quick fix!!
It works as expected.
