### ISSUE TITLE
Does not install on ReadTheDocs.com

### ISSUE THREAD

**Issue by AlbertMietus** [useblocks/sphinxcontrib-needs#26]
For reasons I do not understand, needs will not install in RTD.com. See the log below; I got      AttributeError: '_NamespacePath' object has no attribute 'sort'

Note:: I know, it does run on **RTF.org** (e..g http://sphinxcontrib-needs.readthedocs.io/) But we use it commercial  variant: **.com**; which is slightly different (mainly to support non-opensource).

Note:: The same setup does run on my (Mac-based) PC; both with python-3.4 and python-3.6 

Thanks for needs. Even more thanks, when a new versions becomes available. As this is a showstopper (other issues/suggestions have less prio)

Log
===

> Collecting sphinxcontrib-needs (from -r /home/docs/checkouts/readthedocs.org/..../checkouts/master/docs/requirements.txt (line 11))
>   Downloading sphinxcontrib-needs-0.1.47.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/home/docs/checkouts/readthedocs.org/..../envs/master/lib/python3.6/site-packages/setuptools/__init__.py", line 10, in <module>
>         from setuptools.extern.six.moves import filter, filterfalse, map
>       File "/home/docs/checkouts/readthedocs.org/..../envs/master/lib/python3.6/site-packages/setuptools/extern/__init__.py", line 1, in <module>
>         from pkg_resources.extern import VendorImporter
>       File "/home/docs/checkouts/readthedocs.org/..../envs/master/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in <module>
>         @_call_aside
>       File "/home/docs/checkouts/readthedocs.org/..../envs/master/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
>         f(*args, **kwargs)
>       File "/home/docs/checkouts/readthedocs.org/..../envs/master/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3045, in _initialize_master_working_set
>         dist.activate(replace=False)
>       File "/home/docs/checkouts/readthedocs.org/..../envs/master/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2577, in activate
>         declare_namespace(pkg)
>       File "/home/docs/checkouts/readthedocs.org/..../envs/master/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2151, in declare_namespace
>         _handle_ns(packageName, path_item)
>       File "/home/docs/checkouts/readthedocs.org/..../envs/master/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2091, in _handle_ns
>         _rebuild_mod_path(path, packageName, module)
>       File "/home/docs/checkouts/readthedocs.org/..../envs/master/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2120, in _rebuild_mod_path
>         orig_path.sort(key=position_in_sys_path)
>     AttributeError: '_NamespacePath' object has no attribute 'sort'
>     
> 
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-b2xxkrcn/sphinxcontrib-needs/
>

**Comment by AlbertMietus** [comment]
As a workaround, I forces RTfD.com to use another versions of setuptools.

* After several tries, ``setuptools==34.3.2`` **does work** 
* **NOT** working variant: ``setuptools==36.8.0``
* Didn't try/record others

Those versions are selected purely on google results. See e.g https://github.com/pypa/setuptools/issues/885#issuecomment-278652057

**Comment by danwos** [comment]
The only solution, which sphinx-needs could do, is to force the installation of a specific setuptools version by adding it as dependency to our setup routine.

But as this bug is part of setuptools only, affects other packages as well and sphinx-needs has no functional requirement to a specific setuptools version, my proposal is to do nothing here on our site.

Maybe we could set a red note on the starting page of our documentation that the installation of sphinx-needs works with setuptools version x.y.z only, as long as the bug is not solved.

Any feedback?

**Comment by AlbertMietus** [comment]
Given setup-tools is currently at 38-something; _both 36.* and 34* are "old"._  It does't sound like a great idea, to fix **needs** to that. Besides, those versions are just "try an error" once ... A better fix/workaround would be better. And, searching to that is a more useful spending, as finding a recent version that works ... (Surely there is/will be a version that does/will work:)

On the other hand, documenting the effect and the workaround does help! (Once of the reasons to create this issue (People/Google can find it now)

I would propose an other direction: It seems this issue is related to #27. 
My impression it that setuptools (repeatedly) has have (will have) problems with (multiple packages) using the same namespace. So, with a bit of luck, or a little extra effort, the solution on #27 (which is accepted already) this one will go away.

Testing that is a bit clumsy; but I can do so on RTfD.com (the paid site); Although only an "low prio" weeks :-). And only after a version is available on PyPi ... 

Would that be acceptable?

**Comment by danwos** [comment]
#27 is already fixed inside in 0.1.48 ([Changelog entry](http://sphinxcontrib-needs.readthedocs.io/en/latest/changelog.html#id1))
Which is also available on pypi: https://pypi.python.org/pypi/sphinxcontrib-needs/0.1.48
So your testing offer is highly welcome.

Thanks for all the input and spent time :+1:

**Comment by AlbertMietus** [comment]
Due a project change, I no longer have access to rtfd.com... So no option to test (soon)

Maybe somebidy else. Or just hope for it :-)

**Comment by danwos** [comment]
Ok, good to know and thanks for your commitment. 
I close this issue because the chance is high enough that this issues gets solved by one of the involved external parties(rtd team, setuptools, ...)
