### ISSUE TITLE
Plz use sub package!

### ISSUE THREAD

**Issue by AlbertMietus** [useblocks/sphinxcontrib-needs#27]
Currently, All need*.py files are installed in `sphinxcontrib/` directly. This makes this dir "big and clumbersum".

Most/Other packages are installed inside a sub-dir; at least when the contain several files. This makes my setup a lot better maintainable.

I would like to see this for needs too. And `needs/` would be a nice subdir/package name :-)

Thanks (Thanks for providing ***needs*** too)

**Comment by AlbertMietus** [comment]
This may be related to #26 (google on setuptools)

**Comment by danwos** [comment]
Great idea and fixed.
Will be available on the next release, which should be online very soon.
