### ISSUE TITLE
Support rst/jinja content for roles

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinxcontrib-needs#28]
Currently the role **:need:** does support python strong formats only.
It would be great, if it could fully support RST/jinja2 content, so that we are able to set:

* RST styles like `**bold**`
* CSS selector
* other RST roles/directives

We should also support the other roles need_incoming and need_outgoing.

This issue is bases on a discussion in #25.

**Comment by AlbertMietus** [comment]
This is quite simple, I guess. 
The template-string (as specified in the config) should be feed to jinja2.Template(), see http://jinja.pocoo.org/docs/2.10/api/#jinja2.Template.
Then, that template is render()ed, resulting in a **rst** “string”, to be inserted in source; like currently is done, with str.format()

To make a var  bold, use ``**{{var}}**``, etc

**Comment by danwos** [comment]
Unfortunately  it is not so easy, because needed information for need-links is available only **after** all files with rst have been already rendered and the doc-tree is ready.
So the sphinx-state-machine is far behind the point, where it can render **rst** content.

There seems to be (un-)documented placeholders for this use case, which allows to mark "sections" to be rerendered later. But I haven't worked with them, so I need some time for investigation.

**Comment by danwos** [comment]
Won't fix.
Not sure if this feature is really important and the implementation may be complex.
Therefore i close it.

Feel free to add comments,if it is really important to you.
