### ISSUE TITLE
Register dynamic function from external extension not working.

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinxcontrib-needs#288]
Problem: https://github.com/useblocks/sphinx-test-reports/issues/12

Reason: External extension register their dynamic functions (during initialization) before sphinx-needs prepares its environment (by event).
During this event preparation ``NEEDS_FUNCTIONS`` get cleaned, even if it has already content from external.

**Comment by twodrops** [comment]
@danwos Works as expected. Thanks 👍🏽
