### ISSUE TITLE
Dynamic function: parse return value as rst

### ISSUE THREAD

**Issue by krivi95** [useblocks/sphinxcontrib-needs#291]
Hi, I'm trying to add `user defined dynamic function` which returns `string in rst format`. What I was trying to do is to call that function inside a need and hopefully to have the function return value rendered in the need as rst.

Here is a simplified example to illustrate:
```python
# conf.py

def test_rst_rendering(app, need, needs):
   """Here we're returning a string which in rst should be bold"""

    return "**This should be bold**"

def test_need_content(app, need, needs):
   """And here we're testing if possible to update need content in the function with rst syntax"""

    need["content"] = "**This should be bold**" + need["content"]
    return "content"

needs_functions = [
    test_need_content,
    test_rst_rendering,
]
```

And when used with `our own need_type` (maybe we have to somehow configure our custom need type in order to dynamically render rst from function return value):
```python
class Example:
    """
    .. output:: Example
        :id: OUTPUT_100
        :tags: example

        [[test_need_content()]]
        [[test_rst_rendering()]]
    """
```

What we end up is that none of the functions resulted in rendering output as rst. So trying to modify need content also didn't work:
![image](https://user-images.githubusercontent.com/30963594/122540510-01f4f780-d029-11eb-9220-0961d75e9568.png) 

I was able to see in implementation where the [function call is replaced with the return value](https://github.com/useblocks/sphinxcontrib-needs/blob/71288bddee36bc9b466aac3cd133ae0d718c8a77/sphinxcontrib/needs/functions/functions.py#L215) and that it's executed in the [process_need_nodes](https://github.com/useblocks/sphinxcontrib-needs/blob/71288bddee36bc9b466aac3cd133ae0d718c8a77/sphinxcontrib/needs/directives/need.py#L308).

Does anybody maybe know if something like this is possible to do? Am I maybe missing something out, some config which is not set in order this to work?

***I'm using version `sphinxcontrib-needs==0.6.0`

Many thanks!

**Comment by twodrops** [comment]
@krivi95 Not a solution for the above behavior but is [templates](https://sphinxcontrib-needs.readthedocs.io/en/latest/directives/need.html#template) a solution for this usecase you have?

**Comment by danwos** [comment]
I think this is not possible right now. 2 Reasons:
1) The rst-rendering is done by Sphinx before the dynamic functions get executed.
2) dynamic functions mostly do a simple string-replacement: func-call out, return value in. And that directly on the already rendered docutils nodes. 

There would a way to treat the return value as rst and render it (basic rst only, no sphinx directive support). But then Sphinx-Needs would need to deal with a small docutils node-tree and inject this somehow in the already existing node-tree of the content area.
So .e.g a simple text-node with a dynamic function must get split and the rendered rst-tree somehow integrated.
Possible, but I have the feeling that this would have a lot of corner cases.

Templates are also my suggested workaround.
There are executed earlier.
Drawback: No direct python/script support for dynamic data.
But maybe you could inject a Jinja-statement into the Jinja-Environment and then calculate your values.
Maye this [stackoverflow question about jinja and custom python function](https://stackoverflow.com/questions/6036082/call-a-python-function-from-jinja2) is a good starter.

However, please keep me updated, if you find a solution for your case.
I would be happy to document it and share it with our community.

**Comment by krivi95** [comment]
@twodrops @danwos thanks for detailed explanation and suggestions! 

I wasn't aware that Sphinx was doing rst-rendering before dynamic functions are called, it makes sense now.

Templating might be a way to go, or an only way to go in this case. The dynamic function that I use in the need, under python class/function dosctring, takes some additional arguments in order to dynamically render content for docs. I might have the idea how to use dynamic data in templates using dynamic function.

If I managed to find a workaround I'll share the solution here.

**Comment by krivi95** [comment]
Just a little update on this topic. 

In the end I didn't mange to inject the function to the jinja context so that it would be used by the need template.

What I did as a workaround is using [sphinx-jinja](https://github.com/tardyp/sphinx-jinja) in the need iteself, under docstring.

Here is an example how it could be done:

```python
# conf.py

extensions = [
    "sphinxcontrib.needs",
    "sphinxcontrib.jinja",
    ...
]

def get_rst_test():
   """Function to be called in the jinja template"""

    return "**This should be bold**"

# Adding function to jinja context
jinja_contexts = { "ExampleTemplate": { "get_rst_test": get_rst_test }}
```

And in docstring:
```python
class Example:
    """
    .. req:: Example
        :id: REQ_001
        :tags: example

        .. jinja:: ExampleTemplate
            :file: path/to/jinja/template    
    """
```

Jinja template for rendering rst:
```jinja
{# Template for sphinx-jinja #}

*Function result:* {{get_rst_test()}}

```

**Comment by danwos** [comment]
Nice, that's also a great workaround.
Can I reuse your example from here for the documentation?

I would say we just update the docs and then close this issue, because I see no technical way to support this even better.

**Comment by krivi95** [comment]
Sure, of course!

Thanks for the help and for the work you're doing, I really appreciate it!
