### ISSUE TITLE
needs_extra_options does not support uppercase

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#296]
From the usability point of view a "kebab-case" suits `needs_extra_options` better, but we had a case where we used an uppercase letter in `needs_extra_options` and it either threw an exception or made the need directive invalid.

Incase of an import with needs.json, the option with uppercase appeared as part of the need but not within needtables.
![37f5ec80-d345-11eb-8cb5-c551031e9d50](https://user-images.githubusercontent.com/103930/123063962-262c4c00-d40e-11eb-87f6-72f2f31b3d16.png)

**Comment by danwos** [comment]
Yeah, the name in ``needs_extra_options`` is more a technical name for an option, which must match the Sphinx internal rules for it.

So the implemented way of interpreting it for representation in tables and co. is not really helpful in all cases.

I think this issues don't need to be resolved, if #298 is available, right?

**Comment by twodrops** [comment]
I also like to leave `need_extra_options` with "kebab-case" as it is more usable than having extra keypress for "_" or an uppercase.
I agree that we can address it with #298. I only wanted to verify that it is not an unintended bug as it was throwing an exception or behaving differently between `needtable` and options displayed within needs in the HTML.

**Comment by twodrops** [comment]
@danwos  I guess this can be closed right? Probably, it makes sense to specify this limitation as part of ``needs_extra_options`` documentation and mention #298 as a solution
