### ISSUE TITLE
needpie starts counting with 0 instead of 1

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#297]
The numbers on a needpie are is always lower by a count of 1
![pie](https://user-images.githubusercontent.com/103930/123065732-b919b600-d40f-11eb-8ac3-2f97332403a6.png)

```
.. needpie:: Some Pie
   :labels: verified, accepted, in clarification, rejected
   :explode: 0.2, 0, 0, 0
   :colors: #77ff44, #f7ff00, #ffd022, #cccccc

   type == 'sw_req' and status == 'verified'
   type == 'sw_req' and status == 'accepted'
   type == 'sw_req' and status == 'in clarification'
   type == 'sw_req' and status == 'rejected'

.. note:: Pie chart is counting elements starting with 0.

.. needtable::
   :filter: type == 'sw_req' and status == 'verified'
   :style: table
   :columns: id, status

.. needtable::
   :filter: type == 'sw_req' and status == 'in clarification'
   :style: table
   :columns: id, status
```

**Comment by twodrops** [comment]
Now I see that the count has increased by one than actual. Could it be that it was working correctly before this fix?
Sorry, I did not test the bug myself before reporting and forwarded the bug report from my colleague as it is, but his report clearly pointed to a problem.

Another thought, are needparts, if present, somehow playing a part in the wrong count?

**Comment by danwos** [comment]
Will check again.
It looked like the code rounded numbers down as the calculation is based on the percentage. So e.g. a result was 5.99996 and rounded to 5.
