### ISSUE TITLE
needtable column titles

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinxcontrib-needs#299]
Provide a solution to specify custom titles for needtable columns:

Example:
```
.. needtable::
   :filter: status == "open"
   :columns: id as "ID", title, option_1 as "Number 1", option_3
```

**Comment by twodrops** [comment]
@danwos Thanks. Works as expected. Any reason (as you documented) why "," and ";" are not supported even with escaping them? Also found that "|" is not allowed.

I don't really see a need to support them, only wondering why they were excluded :)

**Comment by danwos** [comment]
The regex may need some enhancements to support more chars like |. :)

For , or ; : The string gets split by these chars before the title  handling is executed.
I didn't want to touch this splitting mechanism in this PR as well, but support for this should be doable.

**Comment by twodrops** [comment]
No issues. I guess it is ok for now and it works as expected.
