### ISSUE TITLE
New feature: Restrict status

### ISSUE THREAD

**Issue by ubmarco** [useblocks/sphinxcontrib-needs#3]
**Feature request**
As a user I want to restrict the values that may occur for the 'status' field so that I can introduce standards for my Sphinx projects.

**Implementation proposal**
New configuration dictionary in conf.py:
```
needs_status_whitelist = {
  '<status_1>': "<status_1_description>",
  '<status_2>': "<status_2_description>"
}
```

**Comment by ubmarco** [comment]
**New implementation proposal**
- conf.py
  New boolean flag `needs_defined_status_only`
- any .rst file
  New directive 'needs_status' which defines a status and outputs nothing
  Fields
  ```
  .. needs_status::
      :name: open
      :description: The need type req is in state open
  ```
- any .rst file
  New directive 'needs_legend_status' which dumps a legend for all status

Optional features (if you have the time)
- More fields for needs_status directive:
```
      :predecessor: <status_name>
      :color: <rgb_color_code>
```
- More fields for needs_legend_status directive:
  ```
  .. needs_legend_status::
      :type: table / diagram
      :add_description: True/False (Usecase for diagram
  ```
  The diagram type will be painted with plantuml (type: node) and uses the predecessor information for status connections

**Comment by danwos** [comment]
Implemented initial proposal only.
