### ISSUE TITLE
needs are placed together when rendered

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#304]
I am not absolutely sure if this was the case before.

I see that if there are multiple needs, they are now rendered together. 
![2021-06-24_17h54_03](https://user-images.githubusercontent.com/103930/123297903-48aa8c00-d518-11eb-94e4-324fde379c6b.png)

Could it be that, there was a empty space separating them before?

**Comment by twodrops** [comment]
I verified with an old document and I guess it indeed is a new bug. See an old document
![2021-06-25_05h07_44](https://user-images.githubusercontent.com/103930/123363786-87216480-d573-11eb-9172-2d92493f0858.png)

**Comment by danwos** [comment]
This is based on the manipulation the rtd theme is doing via javascript.
Issue is related to #305, all discussion there.

**Comment by danwos** [comment]
Handled by #305

**Comment by twodrops** [comment]
Tested using https://github.com/useblocks/sphinx_rtd_theme/tree/danwos/wy-table-exclude. The above problem still exists
