### ISSUE TITLE
Datatable issues when using RTD Theme

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#305]
Some points were reported as part of this issue
https://github.com/useblocks/sphinxcontrib-needs/issues/271#issuecomment-844837720

When using Datatables with RTD,

* The head columns don't have the same width as the content columns.
* When scrolling head and content is not align.

![118938027-723b2b00-b94e-11eb-97a1-63e0179e47ee](https://user-images.githubusercontent.com/103930/123355607-4d962c80-d566-11eb-980a-3d096f184b5d.png)

**Comment by danwos** [comment]
The read_the_docs theme related issues really drive me crazy :/
This theme is doing so much voodoo, that it is hard or even impossible to provide workarounds for it.

So rtd is wrapping **each** table in an extra ``div`` with class ``wy-table-responsive`` (via online javascript manipulation!). 
Then some values for ``div.wy-table-responsive`` get set via **css** and I have the feeling also via **js**.

When I deactivate the **rtd js** file ``theme.js``  for the documentation, all looks good.

So it's impossible to define something on **css** level, if it gets overwritten by **js** code later.

I will need to discuss this issue with the rtd-developers and maybe discuss a common way of how a table (created by extension) can be exclude from this kind of handling.

**Comment by danwos** [comment]
Created bug report: https://github.com/readthedocs/sphinx_rtd_theme/issues/1179

**Comment by twodrops** [comment]
Perfect bug report. Thanks!!

**Comment by danwos** [comment]
Same problem for the Sphinx Material theme.
But the reason and a solution would look completely different:
Bug issue: https://github.com/bashtage/sphinx-material/issues/119

**Comment by danwos** [comment]
PR is out for RTD: https://github.com/readthedocs/sphinx_rtd_theme/pull/1218

**Comment by danwos** [comment]
PR on RTD side is on hold and shall be merged with release 1.1. Currently 1.0 gets prepared, so this may take a while :disappointed: .

In the meantime, this fork contains the change and can be installed by hand to get it working:
https://github.com/useblocks/sphinx_rtd_theme/tree/danwos/wy-table-exclude
