### ISSUE TITLE
needextend throws exception if id is modified

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#318]
``needextend`` shall not allow modification of ``id`` of the need.

```rst
.. needextend:: id == "MY_NEED_ID"
   :id: MY_NEW_NEED_ID
```
At the moment, it does not allow it, but throws an exception. 

>Extension error (sphinxcontrib.needs.roles.need_incoming):
Handler <function process_need_incoming at 0x7f4172c051f0> for event 'doctree-resolved' threw an exception (exception: 'BuildEnvironment' object has no attribute 'warn_node')

It would be nice if the ``id`` modification is ignored (and an error is thrown).

**Comment by danwos** [comment]
The change does not register internal options (currently "id" only") for ``needextend`` in Sphinx.
Then Sphinx decides how to care with it, which is normal writing a warning, ignore it and go on.
