### ISSUE TITLE
need filter 'eval' execution performance

### ISSUE THREAD

**Issue by ubmarco** [useblocks/sphinxcontrib-needs#328]
Hi,
this is about the needfilter/needtable performance in big projects.

Whenever a need filter is used (e.g. in a needtable), the Python builtin `eval` is used on the filter string to check whether a need fulfills the filter requirement or not. Running `eval` on every need for each filter string execution is expensive.

In short, I vote for calculating a Python lambda function with eval upfront for each filter string, so `eval` is only called once for each filter string to reduce build times. Below (simplified) experiment shows that this approach reduces the execution of filtering by a factor of 100.

I did some experiments, here is my Python file:
```python
"""Test for needs filtering."""

import math
import time

NEED_COUNTS = [5000, 10000, 50000]
EXEC_COUNT_PER_FUNC = 10

for need_count in NEED_COUNTS:

    need_to_filter = math.floor(need_count * 7 / 8)
    eval_filter = f"x == {need_to_filter} or x == 1234 or x == 4"
    precalc_eval_func = eval(f"lambda x: x == {need_to_filter} or x == 1234 or x == 4")

    functions = {
        "pure_comprehension": lambda: [x for x in range(1, need_count) if x == need_to_filter or x == 1234 or x == 4],
        "eval_comprehension": lambda: [x for x in range(1, need_count) if eval(eval_filter)],
        "precalc_eval_comprehension": lambda: [x for x in range(1, need_count) if precalc_eval_func(x)],
    }

    for name, function in functions.items():
        start_time = time.time()
        for _ in range(0, EXEC_COUNT_PER_FUNC):
            result = function()
        end_time = time.time()
        print(f"Function {name} executed {EXEC_COUNT_PER_FUNC} times on {need_count} needs:")
        print(f"  output : {result}")
        print(f"  runtime: {end_time - start_time:.3f}s")
    print("\n")
```
The goal of the example is to run a list comprehension to filter a list of numbers for some specific numbers.
There are 3 cases:

1. Run a pure list comprehension
2. Use eval for each execution
3. Use eval upfront to speed up the comprehension with a user-provided filter condition

Each case is called 10 times to simulate 10 needtables.

Here is the output:
```
Function pure_comprehension executed 10 times on 5000 needs:
  output : [4, 1234, 4375]
  runtime: 0.011s
Function eval_comprehension executed 10 times on 5000 needs:
  output : [4, 1234, 4375]
  runtime: 1.081s
Function precalc_eval_comprehension executed 10 times on 5000 needs:
  output : [4, 1234, 4375]
  runtime: 0.021s

Function pure_comprehension executed 10 times on 10000 needs:
  output : [4, 1234, 8750]
  runtime: 0.029s
Function eval_comprehension executed 10 times on 10000 needs:
  output : [4, 1234, 8750]
  runtime: 1.966s
Function precalc_eval_comprehension executed 10 times on 10000 needs:
  output : [4, 1234, 8750]
  runtime: 0.037s

Function pure_comprehension executed 10 times on 50000 needs:
  output : [4, 1234, 43750]
  runtime: 0.120s
Function eval_comprehension executed 10 times on 50000 needs:
  output : [4, 1234, 43750]
  runtime: 10.069s
Function precalc_eval_comprehension executed 10 times on 50000 needs:
  output : [4, 1234, 43750]
  runtime: 0.163s
```
I can observe that a pre-calculated filter string (case 3) has almost the same execution performance as directly running the Python filter (case 1). Calling `eval` over and over again is significantly slower.

This experiment uses a relatively simple `eval` function, in reality filter strings can be quite complex and Python will have to come up with an [AST](https://en.wikipedia.org/wiki/Abstract_syntax_tree) for the whole statement on each call of `eval` to execute it.

**Comment by danwos** [comment]
Great idea and nice explanation.

Looks like you could also use compile() for the expression.

Here is also a SO topic with some discussions:   https://stackoverflow.com/questions/12467570/python-way-to-speed-up-a-repeatedly-executed-eval-statement

**Comment by danwos** [comment]
Realized by above commits/PR.

**Comment by ubmarco** [comment]
Awesome, thanks!
