### ISSUE TITLE
needs_external_needs: Support local needs.json

### ISSUE THREAD

**Issue by arwedus** [useblocks/sphinxcontrib-needs#339]
There is a (well-hidden) option in intersphinx to load the objects.in file from a local directory or one or more mirrors.
I'm looking for a way to load an external needs.json file from a local directory.

This could be solved by adding an optional setting like "json_path", which just loads a file instead of attempting HTTP download.

**Use Case:**

Given two projects, A and B, which are built locally, the following can be used to generate an external-needs mapping:

```
|- project_A/
|  |- build
|  |  |- needs.json
|  |  |- html/
|  |- src/
|  |  |- conf.py
|- project_B/
|  |- build/
|  |  |- needs.json
|  |  |- html/
|  |- src/
|  |  |- conf.py
```

project_B/src/conf.py:

`needs_external_needs = [{json_path = "../../project_A/build/needs.json" ...}]`

**Comment by danwos** [comment]
I think there is also a hidden feature for needs_external_needs to use a local needs.json.
The ``json_url`` can have the format ``file://my/local/path/needs.json``.
So instead of ``http://`` you can use ``file://``.

But this is totally missing in the docs.
So I keep this ticket open, until I have fixed the docs.

**Comment by arwedus** [comment]
well hidden indeed. :-) I ran a local python http server to circumvent the limitation until now.

**Comment by arwedus** [comment]
Please document that the URL has to be `file:///home/local/path/needs.json`, with three slashes after file:

Or else you get this error:

```
Traceback (most recent call last):
  File "/home/str2lr/venvs/sphinx-doc/lib/python3.7/site-packages/sphinxcontrib/needs/external_needs.py", line 24, in load_external_needs
    response = s.get(source["json_url"])
  File "/home/str2lr/venvs/sphinx-doc/lib/python3.7/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/str2lr/venvs/sphinx-doc/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/str2lr/venvs/sphinx-doc/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/str2lr/venvs/sphinx-doc/lib/python3.7/site-packages/requests_file.py", line 34, in send
    raise ValueError("file: URLs with hostname components are not permitted")
ValueError: file: URLs with hostname components are not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/str2lr/venvs/sphinx-doc/bin/sphinx-build", line 8, in <module>
    sys.exit(main())
  File "/home/str2lr/venvs/sphinx-doc/lib/python3.7/site-packages/sphinx/cmd/build.py", line 294, in main
    return build_main(argv)
  File "/home/str2lr/venvs/sphinx-doc/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/str2lr/venvs/sphinx-doc/lib/python3.7/site-packages/sphinx/application.py", line 350, in build
    self.builder.build_update()
  File "/home/str2lr/venvs/sphinx-doc/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    len(to_build))
  File "/home/str2lr/venvs/sphinx-doc/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 306, in build
    updated_docnames = set(self.read())
  File "/home/str2lr/venvs/sphinx-doc/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 402, in read
    self.events.emit('env-before-read-docs', self.env, docnames)
  File "/home/str2lr/venvs/sphinx-doc/lib/python3.7/site-packages/sphinx/events.py", line 101, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/str2lr/venvs/sphinx-doc/lib/python3.7/site-packages/sphinxcontrib/needs/external_needs.py", line 27, in load_external_needs
    raise NeedsExternalException(f'Getting {source["json_url"]} didn\'t work. Reason: {e}')
sphinxcontrib.needs.external_needs.NeedsExternalException: Getting file://home/.../workspace/build/documentation/needs.json didn't work. Reason: file: URLs with hostname components are not permitted
```

**Comment by danwos** [comment]
Ohh thanks for the hint and for testing it.
Then the relative path support is not working.
Will fix this too.

**Comment by arwedus** [comment]
Again: It works for me. IF you spell it `file:///...`

**Comment by arwedus** [comment]
Sphinx-needs doesn't support relative paths to an "external needs" project, though.

This would come in handy for relocatable multi-project build documentation, i.e. if you put the documentation in such a web folder structure:

```
<webroot>
|- master
|  |- project_a
|  |- project_b  # reference project A
|  `  ...
|- release
|  |- 1.0
|  |  |- project_a
|  |  |- project_b  # reference project A
|  |  `  ...
|  |- 1.1
|  ` ...
```

Intersphinx supports this:

```
intersphinx_mapping = {'project_a': ('../../project_a/html',
                                  (os.path.join(project_root, 'build', 'project_a', 'html', 'objects.inv'), None))}
```

Result:

`:doc:` links will be converted to links in the following pattern:

`<relative path to my project root>/<relative path to other project root>/<relative document path>.html`

e.g. if you give have a role :doc:`project_a:tools/index` in a file `project_b/html/doc/design.rst`, the relative link will be:

`../../../project_a/html/tools/index.hml`

It now does not matter whether the documentation is in a relative path master/ or release/1.0/ or release/1.1/

**Comment by Thomas-Swindells-t** [comment]
What would probably be nice from a usability perspective is to check whether the json_url has a scheme component (contains ://), if it doesn't then assume it is a relative path and construct a url in the form file:///<project_root>/<json_url>

**Comment by danwos** [comment]
I agree.
It was a fast solution to ask only for an url and then let the used ``request`` library handle the download.

But now we should do the url vs. path handling by our own, so that it can be more stable.

I like the idea of having another option called ``json_path``.
So the user can decide if he/she uses ``json_url`` or ``json_path``.
And then for ``json_path`` absolute or relative path handling becomes quite easy,

**Comment by arwedus** [comment]
@twodrops  @danwos, sorry, I was out of office in October!

The json_path option works fine but the relative base path feature I requested in [this comment](https://github.com/useblocks/sphinxcontrib-needs/issues/339#issuecomment-888843531) is not yet there. I will create a new issue for it and I hope you can somehow add it to 0.7.3 🙂
