### ISSUE TITLE
Sphinx needs builder should ignore needs_external_needs option

### ISSUE THREAD

**Issue by arwedus** [useblocks/sphinxcontrib-needs#342]
The `sphinx-build -b needs` does not need to download and parse an external needs.json file afaik, because it's only job should be to create a needs.json file on it's own.

I do get errors when providing a needs_external_needs option in the config, though, which could be caused by a non-available remote URL (actually something that could easily happen if a server is down or you work offline) or a non-available local needs.json file - because the "external project" is not built yet.

I helped myself with something like the code below, but instead I would expect the needs builder to not care about the json_url in needs_external_needs.

This is the error I get when needs.json does not exist:

```
Traceback (most recent call last):
  File "/home/me/venvs/sphinx-doc/bin/sphinx-build", line 8, in <module>
    sys.exit(main())
  File "/home/me/venvs/sphinx-doc/lib/python3.7/site-packages/sphinx/cmd/build.py", line 294, in main
    return build_main(argv)
  File "/home/me/venvs/sphinx-doc/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/me/venvs/sphinx-doc/lib/python3.7/site-packages/sphinx/application.py", line 350, in build
    self.builder.build_update()
  File "/home/me/venvs/sphinx-doc/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 289, in build_update
    self.build(['__all__'], to_build)
  File "/home/me/venvs/sphinx-doc/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 306, in build
    updated_docnames = set(self.read())
  File "/home/me/venvs/sphinx-doc/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 402, in read
    self.events.emit('env-before-read-docs', self.env, docnames)
  File "/home/me/venvs/sphinx-doc/lib/python3.7/site-packages/sphinx/events.py", line 101, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/me/venvs/sphinx-doc/lib/python3.7/site-packages/sphinxcontrib/needs/external_needs.py", line 27, in load_external_needs
    raise NeedsExternalException(f'Getting {source["json_url"]} didn\'t work. Reason: {e}')
sphinxcontrib.needs.external_needs.NeedsExternalException: Getting file:///home/me/workspace/build/needs.json didn't work. Reason: Expecting value: line 1 column 2 (char 1)
```

This is my workaround (remember that you can't access the selected builder yet in conf.py):

```
# Include needs from other projects built locally on this machine, using the local needs.json.
external_needs_json_file = os.path.join(project_root, "build", "component_b", "needs.json")
if os.path.isfile(external_needs_json_file):
    needs_external_needs = [
        {
            "base_url": "/component_b/html",
            "json_url": "file://" + external_needs_json_file,
            "version": "0.1",
            "css_class": "external_link",
        },
    ]
```

**Comment by arwedus** [comment]
It actually even gets worse **if** sphinx-build -b needs can find the needs_external_needs file: It then populates the needs.json file with all the needs of the other project. Now this is definitely not what you want in a modular build.

The only fix I see for now is to work with a "generate_needs_conf.py" that does not contain the needs_external_needs file. Or work with external OS environment variables. Both ways are messy.

**Comment by danwos** [comment]
Sorry for the late response.

I think the ``need.json`` should not contain needs by default from external sources like needservices, needimport or external_needs.

So I would update the builder to filter out these objects.

However, even if builder "needs" is used, all the rst-code must get handled the same way as for other builders.
Thanks to features like dynamic function and python code executions in some directives, all data, not matter if defined in rst or downloaded from outside, may be used to calculate values for local needs.
So we can't be sure that everything is working correctly, if Sphinx-Needs does not retrieve all information.
