### ISSUE TITLE
needextend is space sensitive for options

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#349]
``needextend`` does not support space after comma. This is different from the behavior within ``need`` options.

**Does not work**
```
.. needextend:: COMP_SYS_1
   :derives: REQ_SYS_1, REQ_SYS_2
   :+tags: test1, test2
```

**Works**
```
.. needextend:: COMP_SYS_1
   :derives: REQ_SYS_1,REQ_SYS_2
   :+tags: test1,test2
```

**Comment by danwos** [comment]
Looks like tags is working, but all link-options throw exceptions, if it contains a space (or better, if the link does not exist).

Tasks:
- needextend: Remove spaces from link-references names (.strip())
