### ISSUE TITLE
needextend does not add options as a list

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#350]
When ```:+option:``` is used in ``needextend``, it does a string append and not a list append.

```
.. need::
:id: NEED_ID
:tag: tag1
```
```
.. needextend:: NEED_ID
   :+tag: tag2
```

**Resulting need**
```
.. need::
:tag: tag1 tag2
```

**Expected need**
```
.. need::
:tag: tag1, tag2
```

**Comment by danwos** [comment]
I think this is the supposed behavior for extra_options, which contain internally a string.

Only tags, links and extra_links are handled as lists and therefor get a "," between the values.

I also see no way to change it, as a user maybe wants to connect two strings via a ``needextend`` update.

So you could add something like ``, tag2``, but for sure this does not work/look good, if the original need does not contain already a "tag 1"

**Comment by danwos** [comment]
This may get possible with #378, which would introduce extra_option field types.
And then we can decide, if a comma is needed (list type) or  nor.
