### ISSUE TITLE
Role to create need objects

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinxcontrib-needs#373]
To speed up the writing of need objects (req, specs, ...), there shall the possibility to create these objects via a role.

Example:
```rst
Feature X
-----------

This features solves the problem of :req:`how to identify a user` 
by providing a :spec:`login screen for users (id:SPEC_001; status:open)`
and caring about :spec:`role management (links:SPEC_001)`.
```

The representation of such "embedded-needs" is a normal string, which is completely align with the text before and after the need object.

The role-content is separated by the first ``.`` or ``||``. Text before ``.`` is used as title, the rest is the content.
(If ``||`` is used, separation by ``.`` is deactivated for this need).

Basic values can be set by using ``(key:value, key2:value2)`` syntax at the end of the role string.
(But there are not shown as part of the final string!)

Be aware that rst-statements like ``**bold**`` are not supported in role content.

To get a full representation, an author have to use ``needextract``.
For complex manipulation ``needextend`` must be used.

### Use case / Motivation
For smaller projects, which do not have the requirement to follow a tough and standardized process, writing requirements and specifications can be a time consuming burden.

The goal is also, that requirements and co. are not strange process objects, which do not have a real benefit in a user manual. They shall be reusable and useful objects, which can be exported and presented in different ways without any extra costs.

I hope to find the time to update the Sphinx-Needs docs to use this mechanism for feature and problem objects. 
This kind of marking allows me take already existing sentences and just wrap them with the new "need-role" to create objects out of them.

**Comment by haiyangToAI** [comment]
Normally needs objects get created during handling of a directive, which has a run() method to access Statemachine:

        class MyDirective(Directive)
            # configs and init routine

            def run():
                main_section = []

                docname = self.state.document.settings.env.docname

                # All needed sphinx-internal information we can take from our current directive class.
                # e..g app, state, lineno
                main_section += add_need(self.env.app, self.state, docname, self.lineno,
                                         need_type="req", title="my title", id="ID_001"
                                         content=self.content)

                # Feel free to add custom stuff to main_section like sections, text, ...

                return main_section

For a role to create needs objects, it needs also Statemachine. But during the handling of a role, it can't access Statemachine. Hence, close the ticket for now until got further ideas.
