### ISSUE TITLE
Warning in needpie related to mathplot

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#388]
A sphinx-needs execution raises the following warning
```
/lib/python3.8/site-packages/sphinxcontrib/needs/directives/needpie.py:168: MatplotlibDeprecationWarning: normalize=None does not normalize if the sum is less than 1 but this behavior is deprecated since 3.3 until two minor releases later. After the deprecation period the default value will be normalize=True. To prevent normalization pass normalize=False 
```
python==3.8.10
sphinx-needs==0.7.2
sphinx==4.2.0
docutils==0.17.1
matplotlib==3.4.3
matplotlib-inline==0.1.3

**Comment by danwos** [comment]
I'm unable to reproduce the given behavior.

Tested with the current versions and the given ones.
With the official docs and the needpie-test docs.

Maybe this is a strange case when values are 0 or near 0.

**Comment by twodrops** [comment]
@danwos You could use the internally shared sphinx-needs-basics docker example where this could be reproduced.

**Comment by danwos** [comment]
Tested it also there, but still can't find the error in the logs.

Mhh but the installed libs have different versions as above (ok, the issue is also already quite old):
matplotlib==3.5.1
sphinxcontrib-needs==0.7.5

**Comment by twodrops** [comment]
I don't get this warning anymore with the following versions.

```
matplotlib==3.5.1
sphinxcontrib-needs==0.7.7
```

The issue can be closed I guess.
