### ISSUE TITLE
Support "widths" for needtable

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#402]
A "widths" option like in [csv-table](https://docutils.sourceforge.io/docs/ref/rst/directives.html#toc-entry-22) would be nice.

>widths: integer [integer...]
A list of relative column widths. The default is equal-width columns (100%/#columns).

Optionally the following would be nice too.

>width: length or percentage
Sets the width of the table to the specified length or percentage of the line width. If omitted, the renderer determines the width of the table based on its contents or the column widths.

In general it would be good to avoid too many layout options in a needtable as the needtable deals with data and less with presentation. It would however be nice to maintain a balance between the two as some configuration options might be helpful.

Maybe a `style-table` option can be added to set a css class for the whole table as well, similar to [style-row](https://sphinxcontrib-needs.readthedocs.io/en/latest/directives/needtable.html#style-row). This is however really optional as of now.

**Comment by danwos** [comment]
I like the idea to have more options to somehow define the layout/style of a table.
As the needed table presentation can be highly based on the shown data, I  have no problems with some more options to control the final presentation.

I think the options ``widths`` and ``width`` can be provided quite easy, as in our backend all ``needtables`` get transformed to a default docutils table. So we use the same mechanism as ``csv-table``.
The DataTables based tables may make some trouble, as their config is js-based. So DataTables may override some configs.

For your ``style-table`` proposal, I have another, more generic idea.
Most docutils directives provide a generic ``class`` attribute, which sets the related css class for this element.
Sphinx-Needs is internally already using it, but right now there is simply no option configured for the user to set this value as well.
I suggest to open a new issue, which asks for ``:class:`` support in **ALL** Sphinx-Needs directives.
The value is comma separated and the element get set additionally to the ones calculated by Sphinx-Needs.
Would such a feature be what you need? (If yes, I will create a new issue for this).

BTW: Currently there are no options to control the layout/configuration of a DataTable based table.
And DataTable has so many nice features / configuration options to use (amount of elements to show, Export types, Collapsed columns, moveable columns).
If you see any needs to improve this as well, let me know :)
