### ISSUE TITLE
Transform string to link for given need-option

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinxcontrib-needs#404]
The representation of data in Need-Option shall not only contain strings, but also links.

This is currently possible by creating own layouts and dynamic_functions.
But this procedure is quite complex.

This feature shall allow to create automatically links for option-data, based on a given regular expression.
Example: A field named `jira` contains `ABC-123` as content, if `ABC-123` matches a given regex, then 
a link with name `JIRA Issue ABC-123` and url `http://my_jira.server.com/browse/ABC-123` shall be created.

```python
needs_string_links = {
    'jira_link': {
        'regex': "...",   # can contain capture_groups
        'link_url' : "...",  # jinja-string, which gets captured groups as context
        'link_name': '...'  # jinja-string, which gets captured groups as context
        'options': ['status', '...']  #  List of field/option names, for which this link_config is valid
    }
}
```

**Comment by twodrops** [comment]
@danwos We have 404 error with this issue ;) #404
