### ISSUE TITLE
Support relative base_path in needs_external_needs

### ISSUE THREAD

**Issue by arwedus** [useblocks/sphinxcontrib-needs#407]
@danwos  I wrote this request a while ago in [this comment](https://github.com/useblocks/sphinxcontrib-needs/issues/339#issuecomment-888843531) in issue #339 but it should have it's own ticket.

Sphinx-needs doesn't support relative paths to an "external needs" project indeed. I just tested this.

This would come in handy for relocatable multi-project build documentation, i.e. if you put the documentation in such a web folder structure:

```
<webroot>
|- master
|  |- project_a
|  |- project_b  # reference project A
|  `  ...
|- release
|  |- 1.0
|  |  |- project_a
|  |  |- project_b  # reference project A
|  |  `  ...
|  |- 1.1
|  ` ...
```

Intersphinx supports this:

```
intersphinx_mapping = {'project_a': ('../../project_a/html',
                                  (os.path.join(project_root, 'build', 'project_a', 'html', 'objects.inv'), None))}
```

Result:

`:doc:` links will be converted to links in the following pattern:

`<relative path to my project root>/<relative path to other project root>/<relative document path>.html`

e.g. if you give have a role :doc:`project_a:tools/index` in a file `project_b/html/doc/design.rst`, the relative link will be:

`../../../project_a/html/tools/index.hml`

It now does not matter whether the documentation is in a relative path master/ or release/1.0/ or release/1.1/

I don't have an executable example but my config looks like this:

```
# config file of project_b
external_needs_json_file = os.path.join(project_root, 'build', 'project_a', 'needs', 'needs.json')
if os.path.isfile(external_needs_json_file):
    needs_external_needs = [
        {
            "base_url": "../../project_a/html",
            "json_path": external_needs_json_file,
            "css_class": "external_link",
        },
    ]

# output of project_b will be in <project_root>/build/project_b/html
```

While intersphinx actually keeps ".." in relative paths, needs_external_needs seems to simply remove it and replace relative links by absolute links.

**Comment by arwedus** [comment]
any update on this @danwos @haiyangToAI ? I would volunteer to beta test

**Comment by arwedus** [comment]
please reopen this issue, the PR linked does not fix it.

I hardly can imagine how it's going to fix anything, as it doesn't change the source code.

Again, with sphinx-needs 0.7.4, with the following config:

```
external_needs_json_file = os.path.join(project_root, 'build', 'documentation', 'needs', 'needs.json')
if os.path.isfile(external_needs_json_file):
    needs_external_needs = [
        {
            "base_url": "../../documentation/html",
            "json_path": external_needs_json_file,
            "css_class": "external_link",
        },
    ]
```

links in a subdirectory of the project (e.g. `doc/requirements/module_a/spec.rst`) look like this:

```
<div class="line"><span><div class="line">derives from: <span class="derives"><span><a class="external_link reference external" href="../../documentation/html/documentation/requirements/requirements_viewpoint.html#REQ_L1_PER_001">REQ_L1_PER_001</a>, <a class="external_link reference external" href="../../documentation/html/documentation/requirements/requirements_viewpoint.html#REQ_L1_PER_002">REQ_L1_PER_002</a></span></span></div>
```

It's obvious that the relative link must be made "more relative" by adding "../" for each subdirectory level (w.r.t. the build-root) of the .rst in which the respective needs-item is defined.

**Comment by danwos** [comment]
Hi @arwedus ,
you are right, I missed the correct handling of files in subfolders and the fact, that we need to add a relative path to get "back" to the current root path first.
Our tests are only working from files on root level.
