### ISSUE TITLE
Sphinx-needs crashes on import of external needs

### ISSUE THREAD

**Issue by arwedus** [useblocks/sphinxcontrib-needs#441]
I get the following error building a project with external_needs enabled:

```
Traceback (most recent call last):
  File "/home/arwedus/venvs/sphinx-packages/lib/python3.8/site-packages/sphinxcontrib/needs/external_needs.py", line 60, in load_external_needs
    needs = needs_json["versions"][version]["needs"]
KeyError: '0.1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arwedus/venvs/sphinx-packages/lib/python3.8/site-packages/sphinx/events.py", line 101, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/arwedus/venvs/sphinx-packages/lib/python3.8/site-packages/sphinxcontrib/needs/external_needs.py", line 62, in load_external_needs
    raise NeedsExternalException(f'Version {version} not found in json file from {source["json_url"]}')
KeyError: 'json_url'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/arwedus/venvs/sphinx-packages/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/arwedus/venvs/sphinx-packages/lib/python3.8/site-packages/sphinx/application.py", line 344, in build
    self.builder.build_update()
  File "/home/arwedus/venvs/sphinx-packages/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    self.build(to_build,
  File "/home/arwedus/venvs/sphinx-packages/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 308, in build
    updated_docnames = set(self.read())
  File "/home/arwedus/venvs/sphinx-packages/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 404, in read
    self.events.emit('env-before-read-docs', self.env, docnames)
  File "/home/arwedus/venvs/sphinx-packages/lib/python3.8/site-packages/sphinx/events.py", line 109, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function load_external_needs at 0x7f1d07b77430> for event 'env-before-read-docs' threw an exception (exception: 'json_url')

Extension error (sphinxcontrib.needs.external_needs):
Handler <function load_external_needs at 0x7f1d07b77430> for event 'env-before-read-docs' threw an exception (exception: 'json_url')
```

The error disappears when I delete the imported needs.json files.

This is the relevant part of my conf.py:

```
version = "0.1"

# Include needs from other projects built locally on this machine, using the local needs.json.
needs_external_needs = list()
external_fusion_needs_json_file = os.path.join(build_root, "fusion", "needs", "needs.json")
if os.path.isfile(external_fusion_needs_json_file):
    needs_external_needs.append(
        {
            "base_url": "../../fusion/html",
            "json_path": external_fusion_needs_json_file,
            "css_class": "external_link",
        },
    )

external_vision_needs_json_file = os.path.join(build_root, "vision", "needs", "needs.json")
if os.path.isfile(external_pervis_needs_json_file):
    needs_external_needs.append(
        {
            "base_url": "../../vision/html",
            "json_path": external_vision_needs_json_file,
            "css_class": "external_link",
        },
    )

external_planning_needs_json_file = os.path.join(build_root, "planning", "needs", "needs.json")
if os.path.isfile(external_planning_needs_json_file):
    needs_external_needs.append(
        {
            "base_url": "../../planning/html",
            "json_path": external_planning_needs_json_file,
            "css_class": "external_link",
        },
    )
```

The other projects have a version of either "0.1" or "0.1_commit", where commit stands for the first 10 digits of the commit SHA. But the version number should not matter as I leave away the version parameter, right?

**Comment by danwos** [comment]
No, I think it takes the version from the current project, defined in your conf.py. But documentation is missing for this behaviour. Or from current_version in your needs.json. Have to check on Monday.

However, all needs must be stored under a version in needs.json.

**Comment by arwedus** [comment]
they all are stored under a version, but the versions don't necessarily match. However, I used to get a meaningful error message in case the versions did not match. Not sure what to make of it.

Btw. I am testing with current version from https://github.com/useblocks/sphinxcontrib-needs/pull/440

**Comment by arwedus** [comment]
@danwos : This bug is still relevant and makes our build unstable.
We now have all version tags pinned to "0.1" again (but anyhow, the **version should not matter** imO). This is kind of a nasty way to exit, compared to just giving a polite warning message if the json_url  cannot be resolved.

Here's another example:

```
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 278 source files that are out of date
updating environment: [new config] 278 added, 0 changed, 0 removed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sphinxcontrib/needs/external_needs.py", line 60, in load_external_needs
    needs = needs_json["versions"][version]["needs"]
KeyError: '0.1'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sphinx/events.py", line 101, in emit
    results.append(listener.handler(self.app, *args))
  File "/usr/local/lib/python3.8/dist-packages/sphinxcontrib/needs/external_needs.py", line 62, in load_external_needs
    raise NeedsExternalException(f'Version {version} not found in json file from {source["json_url"]}')
KeyError: 'json_url'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/usr/local/lib/python3.8/dist-packages/sphinx/application.py", line 343, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.8/dist-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/usr/local/lib/python3.8/dist-packages/sphinx/builders/__init__.py", line 307, in build
    updated_docnames = set(self.read())
  File "/usr/local/lib/python3.8/dist-packages/sphinx/builders/__init__.py", line 403, in read
    self.events.emit('env-before-read-docs', self.env, docnames)
  File "/usr/local/lib/python3.8/dist-packages/sphinx/events.py", line 109, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function load_external_needs at 0x7f3b81ffaee0> for event 'env-before-read-docs' threw an exception (exception: 'json_url')
Extension error (sphinxcontrib.needs.external_needs):
Handler <function load_external_needs at 0x7f3b81ffaee0> for event 'env-before-read-docs' threw an exception (exception: 'json_url')
+ set +x
Sphinx build finished.
```

the file to be imported looks like this, and both projects have version set to "0.1":

```
│ File: ./../build/fusion/needs/needs.json
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ {
   2   │     "created": "2022-01-28T10:35:30.439208",
   3   │     "current_version": "0.1",
   4   │     "project": "fusion",
   5   │     "versions": {
   6   │         "0.1": {
   7   │             "created": "2022-01-28T10:35:30.439193",
   8   │             "filters": {},
   9   │             "filters_amount": 0,
  10   │             "needs": {
  11   │                 "COMP_FUS_TRW": {
  12   │                     "abbreviation": "",
  13   │                     "accuracy": "",
  14   │                     "asil": "",
```

The conf.py looks like this:

```py
version="0.1"

    if os.path.isfile(external_fusion_needs_json_file):
        needs_external_needs.append(
            {
                "base_url": "../../fusion/html",
                "json_path": external_fusion_needs_json_file,
                "css_class": "external_link",
            },
        )
```

- no version pinned and the versions match, still crash.


Unfortunately this does not happen all the time, just sometimes.

**Comment by danwos** [comment]
Just for me as a note:
The json_url error is based on this logging:
``
File "/usr/local/lib/python3.8/dist-packages/sphinxcontrib/needs/external_needs.py", line 62, in load_external_needs
    raise NeedsExternalException(f'Version {version} not found in json file from {source["json_url"]}'``
    
So needed fix:
- Error message must use json_url or json_path, depending on where it is raised.
- The reason for the Exception raise.

The version mismatch error sounds strange, as there were no problems in the past.
I have the feeling, that the wrong exception gets raised and the reason is something different (file not found, no JSON format, ...).

Will be tough to get a setup, which reproduces this problem.

**Comment by arwedus** [comment]
@danwos : Thanks for picking this up. I think the exception should be caught in this case and a warning message issued only, not a call trace. Maybe it can be made configurable whether a sphinx-needs warning causes the build to fail immediately or continue in a future release?

**Comment by danwos** [comment]
@arwedus: I changed the code a little bit, so that it checks now directly for the correct version.
Also other related exceptions get not caught anymore, so that we should get a meaningful log message.

As I have no test setup right now, which triggers this problem, can you please try the version from #490 with your setup?
I haven't changed any functional yet, except the log-message. So I think the error is still there.

One small thing which came into my mind: Were the needs.json files touched/updated/created by humans or by sphinx-needs only?
Maybe there are some hidden/false unicode-chars in the dict-keys, so that e.g. ``current_version`` and the ``version-key`` are technical not the same, but looks like. I know, strange case, but I had it already in the past.

**Comment by danwos** [comment]
@arwedus: Any update on this from your side? See my last comment. Thanks.

**Comment by arwedus** [comment]
@danwos : We already found out that this is triggered by trying to import an empty needs.json. We have worked around this issue by making sure that even a new project added as skeleton already contains at least one need.

Therefore, I think I should be able to set up a skeleton example project that triggers the exception in sphinx-needs 0.7.5 soon this week, and try out your newest head revision.

**Comment by danwos** [comment]
Ohh thanks, this is really helpful and I think I will be able to reproduce this problem. :+1: 
It's definitely a bug, as empty needs.json should not be a problem.
Fix should be an easy way, but lets see :)
