### ISSUE TITLE
needgantt exception with wrong strftime format string (on windows)

### ISSUE THREAD

**Issue by PhilipPartsch** [useblocks/sphinxcontrib-needs#445]
During execution of building docs from  useblocks / sphinxcontrib-needs repo on a clean Windows 10 / python machine, I got the following exception:

Extension error (sphinxcontrib.needs.directives.needgantt):
`Handler <function process_needgantt at 0x000001A06734FCA0> for event 'doctree-resolved' threw an exception (exception: Invalid format string)`

Issue is with [code line](https://github.com/useblocks/sphinxcontrib-needs/blob/master/sphinxcontrib/needs/directives/needgantt.py#L182):
month = MONTH_NAMES[int(start_date.strftime("%-m"))]
changing it to fix the issue:
month = MONTH_NAMES[int(start_date.strftime("%m"))]

The current value is not according to 1989 specified C Version:
https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes

The fix works fine on my Windows PC. Could someone test the change on a Linux / Unix machine?

**Comment by danwos** [comment]
Strange, that this bug has not been detected since 2 years.
Good finding and thanks for the PR.
