### ISSUE TITLE
needpie option :legend: is not been rendered

### ISSUE THREAD

**Issue by PhilipPartsch** [useblocks/sphinxcontrib-needs#448]
The defined option [legend ](https://sphinxcontrib-needs.readthedocs.io/en/latest/directives/needpie.html#legend) is not working as expected.

**Comment by PhilipPartsch** [comment]
see [pull request](https://github.com/useblocks/sphinxcontrib-needs/pull/449)

**Comment by danwos** [comment]
Thanks also for this finding and the PR.
Will merge it soon.
