### ISSUE TITLE
needpie: figures are not closed

### ISSUE THREAD

**Issue by PhilipPartsch** [useblocks/sphinxcontrib-needs#450]
In needpie the created figures are not closed. This leads to the warning on Windows 10:
`RuntimeWarning from matplotlib: More than 20 figures have been opened. Figures created through the pyplot interface ('matplotlib.pyplot.figure') are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam 'figure.max_open_warning')`

**Comment by PhilipPartsch** [comment]
I reset the matplotlib style to the values of the start of the script. "This is nice."

**Comment by danwos** [comment]
Never have seen this warning before, but I also never had any use cases with more than 20 figure / needpies.

Great finding and thanks for the fix. :+1:
