### ISSUE TITLE
On Windows, calling build() multiple times on the same sphinx.application.Sphinx instance will multiply sphinx-needs css and js entries.

### ISSUE THREAD

**Issue by StephanKuempel** [useblocks/sphinxcontrib-needs#455]
On windows:
Calling build() multiple times on the same sphinx.application.Sphinx instance will add additional sphinx-needs css and js each time, resulting in multiplication of entries in produced html.
Root cause is the usage of pathlib.Path in environment.py  safe_add_file ([environment.py#L34](https://github.com/useblocks/sphinxcontrib-needs/blob/af76b5b4e28e50f569c95a7cf8e9c733f7da5e2b/sphinxcontrib/needs/environment.py#L34])), which will cause a WindowsPath to be rendered.

Forward slashes (/) should be used for src= and href= html entries also on windows.

The problem can bee seen in the debug output:
![debug](https://user-images.githubusercontent.com/84901212/148208382-f3f2438c-3f35-4f39-97b1-2f738eb76885.jpg)

**Comment by danwos** [comment]
Thanks for reporting.
Looks like a bug in the correct calculation of the web path (used local path) and the comparison to what is stored inside app.builder.script_files.

**Comment by danwos** [comment]
I have implemented a fix.
Not sure if it works on windows, as CI is not configured to use windows.
Will fix this with a new ticket.

**Comment by danwos** [comment]
Reopened. Reasons explained here: https://github.com/useblocks/sphinxcontrib-needs/commit/33734dbc9477dc217ff4ee7a4ba85d5541a30c50

**Comment by danwos** [comment]
![image](https://user-images.githubusercontent.com/998700/156378234-d59dcccb-5aaa-4997-9e5c-e0fcc33de493.png)

**Comment by danwos** [comment]
Nice, the added test case in #510 detected the above-described problem on windows builds.
Linux looks good.
See log: https://github.com/useblocks/sphinxcontrib-needs/runs/5397544111?check_suite_focus=true

That's promising and I will take a look soon to fix it finally.

Short hint: The is an identical problem with Sphinx-Data-Viewer, which is used by Sphinx-Needs.
This extension also registers stuff multiple times. Fix for it is on the related main branch, but without any test.
So I'm not sure for the fix works also on windows.
