### ISSUE TITLE
Documented `simple_footer` grid does not exist

### ISSUE THREAD

**Issue by baptoubi** [useblocks/sphinxcontrib-needs#457]
simple_footer grid is documented there : https://sphinxcontrib-needs.readthedocs.io/en/latest/layout_styles.html#grids
and is not implemented in layout.py

**Comment by baptoubi** [comment]
Need to add this to `self.grids`
```
"simple_footer": {
                "func": self._grid_simple,
                "configs": {"colwidths": [100], "side_left": False, "side_right": False, "footer": True},
            },
```

**Comment by danwos** [comment]
Thanks for reporting and providing a solution.
Will try to fix it soon.
