### ISSUE TITLE
Remove logging that cause an error on attribute that should not be defined

### ISSUE THREAD

**Issue by elnino1** [useblocks/sphinxcontrib-needs#458]
When using needs_external_needs, the json_path attribute shall not be defined.
However we have to define an empty value else an error (KeyError: 'json_path') occurs on line 
https://github.com/useblocks/sphinxcontrib-needs/blob/master/sphinxcontrib/needs/external_needs.py#L34

needs_external_needs = [
  {
      "base_url": "http://localhost",
      "json_url": 'http://localhost/needs.json',
      # if not defined, an error occurs
      "json_path": "",
      "version": "0.1.0"
  }
]

**Comment by danwos** [comment]
Thanks for reporting and for the detail report.
I will try to fix it with the next release.

**Comment by David-Le-Nir** [comment]
If you want I'm working on a PR for that som you may want to assign me.
(my implementation is just to remove the line 34 highlighted in description)
I just wait for the 459 to be fixed then I'll rebase to get the unit tests part that I'm missing.

**Comment by danwos** [comment]
Ohh that would be nice.
Thanks for the commitment.
