### ISSUE TITLE
missing extra blank line

### ISSUE THREAD

**Issue by weegreenblobbie** [useblocks/sphinxcontrib-needs#46]
https://github.com/useblocks/sphinxcontrib-needs/blob/f06291acae75de53f76cfacfc0390700eb9658dd/sphinxcontrib/needs/needs.py#L52

I'm getting a warning for each use of this directive:

    WARNING: Explicit markup ends without a blank line; unexpected unindent.
    WARNING: Explicit markup ends without a blank line; unexpected unindent.
    WARNING: Explicit markup ends without a blank line; unexpected unindent.

Adding a blank line here solves it.

**Comment by danwos** [comment]
Thanks @weegreenblobbie for bug report and also for a solution.

I just have fixed it and released it under 0.2.1:
http://sphinxcontrib-needs.readthedocs.io/en/latest/changelog.html#id1

Feel free to test it and give me some feedback.
