### ISSUE TITLE
Support secure storage of tokens for needservices 

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#491]
Several needservices needs tokens to be made available in conf.py. The only way to make them available currently is using ENV variables which is not secure as well. 

It would be nice to have an integration to some kind secure storage in Python (like Java Keystore if something like this exists for Python)  or an interface to configure/implement access to KeyVaults (like Azure KeyVault ) or GitHub Secret etc.

**Comment by twodrops** [comment]
This could be a feature in https://github.com/useblocks/sphinx-needs-enterprise as well. Feel free to move the issue there.

**Comment by danwos** [comment]
I'm not sure if this should be a Sphinx-Needs feature.
Sphinx-Needs only asks for a value in a config-var. Where this is coming from and what mechanism is used to get it, is for me not a task of Sphinx-Needs.
And as the config is stored in a python file, any lib or tool can easily be used. 

And there are so many "secret" related tools/services, that Sphinx-Needs will always support the wrong one for some users.
And adding more than one would mean a lot of maintenance.

So from my side, I'm not fully convinced :) But open for any discussion.

**Comment by twodrops** [comment]
> Sphinx-Needs only asks for a value in a config-var
Oh yes, you are fully right on that.  I agree too that it is not a sphinx-needs feature. 
Closing the issue.
