### ISSUE TITLE
New feature: Directive legend for tags

### ISSUE THREAD

**Issue by ubmarco** [useblocks/sphinxcontrib-needs#5]
**Feature request**
As a user I want to dump a legend of used tags with meaning into the documentation so readers of the documentation know what my tags mean.

**Implementation proposal**
New directive `needs_legend_tags` prints a sphinx table with 2 columns 'tag' and 'description'.

**Comment by danwos** [comment]
See #6. Same arguments...

**Comment by ubmarco** [comment]
See #2 
Closed.
