### ISSUE TITLE
Error on successive sphinx build with needs_pie

### ISSUE THREAD

**Issue by StephanKuempel** [useblocks/sphinxcontrib-needs#505]
Using the sphinx api, successive sphinx builds containing a needs_pie directive lead to error:
```
sphinx.errors.ExtensionError: Handler <bound method ImageCollector.clear_doc of <sphinx.environment.collectors.asset.ImageCollector object at 0x00000203622DB7F0>> for event 'env-purge-doc' threw an exception (exception: 'str' object has no attribute 'discard')
```
This error is caused by the env.images containing wrongly structured entries from needs_pie, e.g.:
```
'../common/images/bsTixl/left-turn.png': ({'../featuresBs/bsTixl/overview'}, 'left-turn.png'),
'../common/images/range_checks/sit_bs_range_checks.png': ({'../featuresCommon/ose/oos_evaluation_feature'},'sit_bs_range_checks.png'),
 '_images\\need_pie_2566d.png': ['_images', 'need_pie_2566d.png'],
 '_images\\need_pie_e4071.png': ['_images', 'need_pie_e4071.png'],
```

A fix for this error would be to provide the correct entries in needpie.py (and also needbar has these) using env.images.add_file instead of mangling with the images dictionary directly:
```
env.images.add_file(fromdocname, rel_file_path) 
```
instead of
```
env.images[rel_file_path] = ["_images", os.path.split(rel_file_path)[-1]]
```

**Comment by danwos** [comment]
Thanks for reporting.
Is there any code snippet, how I can use the Sphinx API to call the build for a project?

And when I got you correct, the error has never shown up in a normal build (with `make` or `sphinx-build`).

**Comment by StephanKuempel** [comment]
I'm using a small wrapper class for this:

```
import sphinx.application

...

class SphinxBuilder:    
    
    def __init__(self, sourcedir:str, outputdir:str):

        doctreedir = os.path.join(outputdir,".doctrees") # use same default as in sphinx\cmd\build.py 
        self.sphinx = sphinx.application.Sphinx(
            srcdir=sourcedir,
            confdir=sourcedir,
            outdir=outputdir,
            doctreedir=doctreedir,
            buildername="html"
        )

def build(self):
        self.sphinx.build()
```

**Comment by StephanKuempel** [comment]
I remember @twodrops mentioning this error also with normal sphinx-build. But i cannot reproduce.
The question is, why was this code ´´´env.images[rel_file_path] = ["_images", os.path.split(rel_file_path)[-1]]´´´ used in the first place ? How is it tested ?

**Comment by twodrops** [comment]
@StephanKuempel  Sorry, looks like I confused between two errors/warnings. The one I get during the build is

```
/usr/local/lib/python3.8/dist-packages/sphinxcontrib/needs/directives/needpie.py:168: MatplotlibDeprecationWarning: normalize=None does not normalize if the sum is less than 1 but this behavior is deprecated since 3.3 until two minor releases later. After the deprecation period the default value will be normalize=True. To prevent normalization pass normalize=False 
  wedges, _texts, autotexts = axes.pie(sizes, **pie_kwargs)
```

This is the one I reported here #388

**Comment by danwos** [comment]
Hi @StephanKuempel,
I tried to add a test case to trigger the found bug.
But the test case passes without any problem.

Can you have a quick look?
Maybe I forgot something.
PR #509 
Line: https://github.com/useblocks/sphinxcontrib-needs/pull/509/files#diff-170e7265363eb1bf298db88b0c1b722ecc1a3955bb880f8b644617beacb0949aR25

**Comment by StephanKuempel** [comment]
Big thanks for adding this. Just had a quick look, the test looks good.
Maybe there has to be a change in at least one source doc for the env_purge event to happen and cause the fault.
I will check out and test tomorrow.

**Comment by StephanKuempel** [comment]
Look like what i wrote above, a change in an .rst file has to be present in between the two builds to cause the error.
