### ISSUE TITLE
need-role bug for imported needs

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinxcontrib-needs#508]
A bug was reported the me for the `need`-role.

If needs got imported via `needimport`, `:need:` is no longer able to reference it and throws an error about a not found need-id.

This bug got introduced with `0.7.6`.

**Comment by arwedus** [comment]
@danwos , the need role all in all seems to be broken.
I get this error even for needs which are defined in the same file!

```
Needs: linked need REQ_SYS_SG14-327 not found (Line 1166 of file ...)
```

The links are also not resolved. My projects do not use needimport, and these aren't external needs either.

**Comment by arwedus** [comment]
@danwos can you create a bugfix release soon?

**Comment by danwos** [comment]
I'm already on it, but have problems to reproduce the error in a test case.
It looks like not all `need` roles are triggering this error.

But I see the bug also in our docs.

When I have a bug fix, I will create also a release for it.

**Comment by danwos** [comment]
I'm getting the feeling that this error may have something to do with an incremental build (I don't know why).

I see the error on our hosted docs (see links under **Example**):
![image](https://user-images.githubusercontent.com/998700/156738160-a2d8c300-6c54-47a5-b7fd-67b6c43d9c15.png)

But when I build the same docs locally, it all looks good
![image](https://user-images.githubusercontent.com/998700/156738313-358b2c74-ddea-479b-beb2-b358c2ec647a.png)

Also the added test case from #512 detects no errors.

@arwedus: Can you confirm, that this errors happens also on a clean build?

I keep trying to reproduce it ...

**Comment by danwos** [comment]
Got it, reason was a new ``upper()`` on an ID, so that the comparison of some stored IDs with lower chars did not work anymore.

If tests passes, it should be released today.

**Comment by arwedus** [comment]
works again, thanks for the quick bugfix release

**Comment by twodrops** [comment]
I can confirm too that the bugfix in 0.7.7 works. Thanks again.
