### ISSUE TITLE
Datatables Export PDF Orientation

### ISSUE THREAD

**Issue by kreuzberger** [useblocks/sphinxcontrib-needs#529]
How and there can i customize the pdf export of datatables. I need no complex styling, just e.g. the orientation should / could be changed to landscape?

**Comment by kreuzberger** [comment]
To clarify: I do not mean the pdf/latex output in sphinx.
I use a normal html builder to "generate" my requirement documentation with sphinx-needs.
I use .. needtable:: to display filtered requirements. If i choose "style" datatables, the export to csv and pdf "buttons" are displayed in the html. If activated, i get an pdf from the current table. I think this goes through a sphinx-needs specific js/html/ toolchain, not via sphinx pdf/latex build step.
Question is how this export can be configured/customized/patched to get e.g. landspace pdf output.

**Comment by danwos** [comment]
Ohh, got it now :)
This is currently not possible.
This feature is provided by the used JS l8b Datatable, which needs to be configured to change the pdf export.

Here is a discussion how this could be done: https://datatables.net/forums/discussion/41263/add-fixed-header-and-footer-to-exported-pdf-file

However, Datatable config is currently fixed coded by Sphinx-Needs and there is currently no way to change this. But it would be a nice improvement.

**Comment by danwos** [comment]
I close this, as this feature is out of scope for sphinx-needs.
