### ISSUE TITLE
Docker for Sphinx-Needs

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#531]
An "official" docker image for sphinx-needs is missing.
https://github.com/tlwt/sphinxneeds-docker does not seem to be maintained anymore.

I would like to contribute the one we are using internally since an year now. 
Incase you would like to have it, could you please create a new repo, for example,  "sphinxneeds-docker"

**Comment by danwos** [comment]
I'm not sure if a dedicated docker image for Sphinx needs makes sense.

Maybe a more generic image for Sphinx in Industry Environments would be more helpful.
For sure it would contain Sphinx-Needs as well

**Comment by twodrops** [comment]
Ok.

These are the contents of the two base images we are using. I do not see anything specific for Industry in these and IMHO this could come in handy for anyone wanting to start with Sphinx and Sphinx-Needs.

## Image Variants
The sphinxneeds images come in two flavors, each designed for a specific use case containing sphinx-needs. 

### `sphinxneeds:<version>`
This is the defacto image (size ~ 460M). If you are unsure about what your needs are, you probably want to use this one. It is designed to be used both as a throw away container (mount your source code and start the container to start your app), as well as the base to build other images off of.

#### Included Tools

The image includes the following tools.

| Tools                                       |   
| ---------------------------------------------- | 
| graphviz |
| jre |
| latexmk |
| texlive |
| open-needs-ls |
| plantuml |
| python |
| sphinx |
| sphinxcontrib-needs |
| sphinxcontrib-plantuml |

### `sphinxneeds:<version>-slim`
This image does not contain the common packages contained in the above version and only contains the minimal packages needed to run sphinxneeds (size ~ 200M). Unless you are working in an environment where only the sphinxneeds image will be deployed and you have space constraints, we highly recommend using the default image of this repository.
 
#### Included Tools

The image includes the following tools.

| Tools                                       |   
| ---------------------------------------------- | 
| python-slim |
| sphinx |
| sphinxcontrib-needs |

**NOTE** Features such as report generation or PDF generation are not supported in this image. Please use the full-version above for such usecases.

**Comment by twodrops** [comment]
@danwos 

Could you please add the useblocks Docker Hub credentials as secrets to this repo?
```
secrets.DOCKERHUB_USERNAME
secrets.DOCKERHUB_TOKEN
```

**Comment by danwos** [comment]
@twodrops: Dockerhub secrets got added.
