### ISSUE TITLE
needs_default_style seems to be not used for PDF output

### ISSUE THREAD

**Issue by MaxQuid** [useblocks/sphinxcontrib-needs#543]
Hi,

I'm using Sphinx with Sphinx-Needs to generate our document in HTML and PDF format.
The conf.py is configured to use the **simple_footer** layout, with a **clean** style.
For the HTML output, the result is perfect.
But for the PDF output, we still have borders.

HTML:
![html_output](https://user-images.githubusercontent.com/105300311/167786086-f57a8a6c-3733-4020-88c9-8ceadd4d804b.png)

PDF:
![pdf_output](https://user-images.githubusercontent.com/105300311/167786160-3b15267a-e5f3-461d-91fe-1a8ac0fa0ef7.png)

How could I remove them?

conf.py:
```
# Define own layout
needs_layouts = {
    'ACTIVE': {
        'grid': 'simple_footer',
        'layout': {
            'head': ['**<<meta_id()>>**'],
            'footer': ['*Covers: <<meta("covers")>>*',
                     '*Architecture: <<meta("architecture")>>*']
        }
    }
}

needs_default_layout  = 'ACTIVE'
needs_default_style = 'clean'
```

Sphinx: v4.4.0
sphinxcontrib-needs: 0.7.9

Thanks a lot

**Comment by danwos** [comment]
Ohh nice layout and welcome to Github :)

But I'm afraid to say that I don't know much about the PDF generation and the underlying LaTex system.
So I have to guide you to the official Sphinx docs about this topic: https://www.sphinx-doc.org/en/master/latex.html

Some of our users use a different approach to get a PDF: They create the PDF from HTML output.
So they use a different, more clean HTML theme and then use one of the available HTML2PDF converters to get a PDF.
This typically allows you to customize the layout by providing self-written CSS files, which may be much easier than customizing a LaTex template.

I think there is also a Sphinx Extension available for this approach, but I'm not sure...

**Comment by MaxQuid** [comment]
Thank you for your answer.
Unfortunately, I cannot convert my HTML output to PDF because I have to use a specific template for my PDF generation (template provided by the company, with footers, headers, and other ugly styles).
I already read the Sphinx docs, but I didn't fount anything about the layout :s

**Comment by danwos** [comment]
All I can say is that each Sphinx-Needs specific node inside the docutil-doctree gets its Sphinx-Needs specific class or even unique identifier.
So if this information is still available in a LaTex output (and I hope so), then it should be identifiable by LaTex-specific style commands. 

But as I have no knowledge about the LaTex details, I wish you good luck.
And if you find a solution, you maybe can share it with me. So that I can put it into our documentation. :)
