### ISSUE TITLE
possible logic bug in `diagrams_common`

### ISSUE THREAD

**Issue by danieleades** [useblocks/sphinxcontrib-needs#570]
https://github.com/useblocks/sphinxcontrib-needs/blob/95e51277393ff32081db6c3b8195b1a7565b7995/sphinxcontrib/needs/diagrams_common.py#L94

just want to query the logic here. if `self.options["show_legend"]` is present and false, this returns `False`. If the value is present and `True`, then the expression also returns false because the `is None` assertion fails. If the value isn't present, then it defaults to `False`, and the expression returns `False` due the `is None` comparison. It returns `False` no matter what, right?

what are the intended semantics?

**Comment by danieleades** [comment]
by the way, all of these dictionaries would be better as concrete classes...

**Comment by danwos** [comment]
``show_legend`` is a flag, so it has no value and the key is only present, if set in rst-code.

So the logic is fine, but ugly: 
```
.. needflow::
   :show_legend:

--> leads to -->

self.options['show_legend'] = None  #  That's how it is set by Sphinx.
```
In this case, the result should be ``True``.

But for sure, it would be much easier to check for the key:
``show_leggend = "show_legend'"in self.optins.keys()``

**Comment by danieleades** [comment]
Ah thanks for the explanation

Actually I think this could be just

```python
show_legend = "show_legend" in self.options
```

Will open a PR to test
