### ISSUE TITLE
Improve Error Message for Missing Requirement ID

### ISSUE THREAD

**Issue by tlovett** [useblocks/sphinxcontrib-needs#59]
When `needs_id_required` is `True`, then the extension will fail the build with an InvalidNeedsException, but the message is not very helpful as it does not tell the user which requirement is missing the requirement ID.  If the project is large it can be difficult to find the offending requirement.

Example:
``An id is missing for this need and must be set, because 'needs_id_required' is set to True in conf.py``

I'd suggest enhancing this error message to provide better guidance on where to locate the error such as document name, line number, and/or requirement content.

**Comment by danwos** [comment]
Done (0.5.0), following exception text gets now raised:
```
"An id is missing for this need and must be set, because 'needs_id_required' "
"is set to True in conf.py. Need '{}' in {} ({})".format(title, docname, lineno))
```
