### ISSUE TITLE
New feature: Directive legend for status

### ISSUE THREAD

**Issue by ubmarco** [useblocks/sphinxcontrib-needs#6]
**Feature request**
As a user I want to dump a legend of used status with meaning into the documentation so readers of the documentation know what my status mean.

**Implementation proposal**
New directive `needs_legend_status` prints a sphinx table with 2 columns 'status' and 'description'.

**Comment by danwos** [comment]
Maybe it is much easier for the document writer to add a simple table and add the needed information.

Currently sphinx-needs does not store any kind of a description for a status, because from the technical point of view this is not necessary.

**Comment by ubmarco** [comment]
In #2 and #3 I described a configuration option which contains a description. Sure I could add a table manually but I might not catch all used status (if not actively configured in conf.py).

**Comment by ubmarco** [comment]
See #3 
Closed.
