### ISSUE TITLE
CI broken, because of setuptools in sphinxcontrib-plantuml

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinxcontrib-needs#619]
The Linting workflow of our CI does not work.

It looks like the reason is **poetry** and the fact, that **sphinxcontrib.plantuml** is importing setuptools inside it `setup.py` file.

```
ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
```
Source: https://github.com/useblocks/sphinxcontrib-needs/runs/7005878217?check_suite_focus=true#step:6:119

It seems to happen for 1-2 days.

I tried a lot of stuff, but couldn't solve it: #618

@danieleades: Do you have an idea, of what we can do here?

**Comment by danieleades** [comment]
sure. take a look at #608
