### ISSUE TITLE
Performance Issue - add_sections

### ISSUE THREAD

**Issue by tlovett** [useblocks/sphinxcontrib-needs#63]
I've discovered a performance issue on large documents and it's related to the add_sections in need.py.  The call to .as_text() in get_sections compounds greatly as the number of sections and documents grows.  

I'll need to find a more efficient was to get the section names.

**Comment by tlovett** [comment]
During profiling, I found another hot spot in need.py's ``process_need_nodes``.  This method has n^2 behavior because it has a nested loop through every need to establish the back links.

```python
        needs = env.need_all_needs
        for key, current_need in needs.items():
            current_need["links_back"] = []
            for linked_key, linked_need in needs.items():
                if current_need["id"] in linked_need["links"]:
                    current_need["links_back"].append(linked_need["id"])
```
This can be simplified so you only need to iterate of all needs once, and then just do a dict lookup for the parent need.  On our internal doc, making this changed dropped time in this method from 4.2s to 0.014s.

**Comment by danwos** [comment]
Okay looks like the pull request introduced some errors.
I get multiple links of the same target inside a need:
![image](https://user-images.githubusercontent.com/998700/43144332-275be14c-8f5d-11e8-8243-411b29e33cf7.png)

**Comment by danwos** [comment]
I got also an KeyError with `needs[link]["links_back"]`, that links_back is not a valid key.
Restarting the build fixes this somehow?! Currently I was not able to reproduce this.
You can push your changes. I will integrate them locally and do some further research based on my problematic sphinx-project.

**Comment by tlovett** [comment]
OK, I pushed up the changes up.  I'm really not sure how you could get KeyError since links_back is set on every need.  I wonder if the new code was run on a pickled environment and that was the problem.
