### ISSUE TITLE
Need copy/mirror: Showing the same need at different places

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinxcontrib-needs#66]
It may be helpful to show the same need at different places.
My use case:
* A system engineer is describing the function/behavior of a SW as needs
* The outcome is a flat list, which may be sorted or not
* A developer takes this list and must map the described function/behavior to a technical sw architecture
* So the developer creates chapters and headlines based on the sw architecture and wants to link/repost the needs.

The mapping could already be done by using filters and references.
But it is hard to read these list and follow always a link to see the content of a need.
Having e.g. a single section, which contains all related functional needs including their content would be helpful.

Drawbacks:
The mirrored needs must not be part of lists or references.
Also a new internal sphinx-target is needed. 
So just taking the data of a need and calling related need-methods again will not work.

**Comment by danwos** [comment]
Maybe this should be realized by a new filter-based directive `.. needmirror::` which "copies" all found needs to the related place.
The representation of a copied need would be the same as the original one.
Maybe a new, automatic set attribute `mirrored: ID` would be helpful to identify easily a mirrored need in the final documentation.

**Comment by tlovett** [comment]
What about enhancing needlist to handle this use case?   I think copying a single need would one use case, but you may want to grab a set of requirements as well.

If you allowed needlist to take a set of IDs (you could use filter, but probably easier if you give them a specific field), and then a new flag to like like ``show_full`` or ``show_copy`` then it could just render the 1 or more needs.

Conceptually this directive already does this, but the output format is simply restricted today.

**Comment by danwos** [comment]
I would like to have a new directive, so that we will be able to have specific options for this directive only.

In the past (pre 2.0) there was the `needfilter` directive only.
But over the time I needed to introduce specific options for tables, lists or diagrams.
The code and the documentation became really complex. 
That were the reasons why `needlist`, `needtable` and `needflow` have been created.
I see the same upcoming problems, if `needlist` should be able to show a "mirror" instead of a list.
E.g. tags need to be added, a "mirror" attribute should be set if a flag is given... All options which can not be used for a normal list.

But the implementation should be doable, as the general fillter-functions are already shared by needlist, needtable and needflow. So no need to reinvent the wheel for the filter capabilities .

**Comment by ubmarco** [comment]
Another proposal for a name would be `needextract` or `needdump`. The directive does not actually create a new need, it is still in its original location. It's just an alternative representation of a need created somewhere else. The directive should support the new layout structure in #102 as well as filters. This enables the user to represent any group of needs in any format he/she likes.

**Comment by danwos** [comment]
Implemented with version 0.5.1.
See [needextract](https://sphinxcontrib-needs.readthedocs.io/en/latest/directives/needextract.html#needextract).
