### ISSUE TITLE
needs_template and needs_template_collapse removed?

### ISSUE THREAD

**Issue by tlovett** [useblocks/sphinxcontrib-needs#69]
We currently customize the template for needs in our projects, and I noticed that the feature says it was deprecated in 0.3.0, but it was actually completely removed.  Deprecation normally implies it is still supported, but discouraged from use.

Can you elaborate on why this feature was removed?

I do see that the extra options are now included by default, but there are some differences:

- Previously if you had an RST link as the attribute value it would be rendered as a link, but now it is not and just shows the raw RST text.
- We also used a custom template when rendering for PDF (we generate it from HTML) that removed the expansion arrow and all attributes.  It looks like the only way to remove the attributes is to specify the full list to hide.
- We had not yet implemented this yet, but we were in discussing enhancing the template to render a requirement differently depending on the attributes.  We have some requirements that are are forward-looking, and we wanted to add an attribute on when they are enforced.  If the release is in the future, then the requirement would be rendered slightly different.  This is admittedly an advanced use case of the template customization, but I'm not clear of any way to do this now without hand-coding a dynamic function on each requirement.

I'm sure we can make our way without the feature, but we did find the custom templates useful.  I would suggest the documentation be updated to not use the term deprecated in either case.

**Comment by tlovett** [comment]
For the 1), would you be open to a feature that used a regex to convert links to reference nodes?  I had messed around with something similar in needtable once before, but never used it.

On 2),  I agree we can likely address it with CSS.

ON 3), the intent was to have some content and formatting appear so there would have been a conditional in the template.  However, it looks like some additional feature enhancement would be needed to handle this, or a really sophisticated CSS selector and a dynamic global option.

I'm OK closing this issue.

**Comment by danwos** [comment]
For your idea to 1) :
Yes, I'm absolute open to it.
Just for my understanding, shall also inline urls be replaced by a reference node?
E.g. "See http//... for more". Or only pure links, like "https://see.more/here.html" .
Last one should be easily doable. The first one could be a little challenge.
