### ISSUE TITLE
Needs overflow the diagram image

### ISSUE THREAD

**Issue by danielvasas** [useblocks/sphinxcontrib-needs#7]
When there are so many needs, that they do not fit horizontally the plantuml image, they overflow the image border.

**Comment by danwos** [comment]
Not sure this can be fixed, as the problem may be on plantuml's side.
As there is another issue for supporting other diagram builders #8 , I would like to implement this and see if this would be a valid workaround.

**Comment by ubmarco** [comment]
There is an unanswered question on [StackOverflow](https://stackoverflow.com/questions/41126177/plantuml-set-max-width-without-constraining-height). From my experience it is not possible with Plantuml to restrict the width. Options are:

- Set layout `left to right direction` vs `top to bottom direction`
- Scale the whole image, which would make the font smaller too.

I'd suppose to give users the option to choose the layout.
