### ISSUE TITLE
Problem with css for needtable.

### ISSUE THREAD

**Issue by townsendbt** [useblocks/sphinxcontrib-needs#77]
![image](https://user-images.githubusercontent.com/40973902/49004185-b2b2f700-f19e-11e8-9691-ef5f333a073b.png)

I'm using the RTD theme. I've changed the width of the content area to be max-width: None

The needtable renders with the table and export buttons and search at the same level. I presume the table should be below the buttons. I tried using the default RTD width/styling and I don't see the table at all. css is not my thing so I really don't know what to change. Is there a quick fix for this?
Cheers.

**Comment by townsendbt** [comment]
Thanks a lot for the quick response. Unfortunately, no joy with the 100% :-(

**Comment by danwos** [comment]
Sorry, I close this issue as I can not reproduce it.
I guess that some self-written css rules for other parts of the webpage are somehow geting involved here and produce the problem.

**Comment by danieleades** [comment]
i'm seeing issues with needtables when using the 'read the docs' theme also.

The contents of the tables are invisible on wide viewports. If i narrow the browser the table reappears. Only seems to occur with the read-the-docs theme (the default 'alabaster' theme doesn't show this issue)
