### ISSUE TITLE
Diagram layout for need parts

### ISSUE THREAD

**Issue by ubmarco** [useblocks/sphinxcontrib-needs#83]
I have the need types `spec` and `test`.
I use need-parts in `spec` and refer to these need-parts from the `test`s.
The `test`s do not refer directly to the parent `spec`.

When generating the diagram with `needflow`, I get
- a box for each `spec`
- a box for each `spec` need part
- a box for each `test`
- arrows linking from the `test`s to the linked `spec` (to the parent `spec`, not to the need part boxes); each arrow has the need part text attached to it
- no arrows from `test`s to the need parts boxes

I propose to change the behaviour:
- a grouping box for each `spec`
- a box for each need part within the grouping box of the corresponding parent `spec`
- a box for each `test` (as before)
- an arrow from each `test` to the corresponding need part (or to the parent `spec` if it is linked).

**Comment by danwos** [comment]
Thanks for reporting.
Have added better need_part handling for needflow.

![image](https://user-images.githubusercontent.com/998700/59969066-83eadc80-9545-11e9-88e0-37b76a4690e0.png)

Release will follow in the next days
