### ISSUE TITLE
content_only option

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinxcontrib-needs#87]
There shall be an option for a need called ``content_only``.
If set, only the content will printed in the normal output of a sphinx build.

There may be layouts/styles for html, which allow via javascript a popup/replacement of the content with the whole need.

### use case
needs shall be part of a normal user manual.
But for the user, the need data is not really important. In most cases only the content needs to be known.

To avoid a copy of a sentence/paragraph from a user manual to a need-specification at another place, all not important need-data shall be invisible and only viewable by button click.

Maybe together with #66 the complete need can be represented somewhere else, outside the scope of a normal user.

**Comment by hkaimio** [comment]
It would be even better if it was possible to control what header information is displayed. We often would like to hide the title of a need (for the reasons you describe above) but show certain custom fields in printed documentation.

Also, please make the solution work also in Latex/PDF output. CSS is fine for web use but there is still need for printed/PDF documentation as well :)

**Comment by danwos** [comment]
@hkaimio: I think every mentioned use case can be handled with release 0.5.0.
See documentation chapter: [Layouts](https://sphinxcontrib-needs.readthedocs.io/en/latest/layout_styles.html).

The layout "focus" shows only content now.
By providing own layouts, really every information and its location can be controlled.
