### ISSUE TITLE
needs.json generation

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinxcontrib-needs#9]
The needs.json file should be generated everytime for each target.
Abd it should be part of the build folder/artifacts.

Therefore an extra generation step is not necessary.

**Comment by danielvasas** [comment]
Suggestion: I think it shouldn't be generated to build folder/artifacts, because this is a versioned file, and that folder is gitignored. I think it should go to just docs (and maybe manually copied to somewhere else if desired).

**Comment by danwos** [comment]
I came to the conclusion that the needs-builder should act like all other sphinx builders in the sphinx environment.
Therefore the needs.json gets now generated inside "_builds/needs/"
With 0.1.33 I will remove all configs, which specifies export path or export file name.

If this file needs some versioning or renaming, the user must copy it by himself to another location.
