### ISSUE TITLE
Needflow missing links since 0.3.11

### ISSUE THREAD

**Issue by 2Eagle2** [useblocks/sphinxcontrib-needs#90]
The following code:

`.. req:: My first requirement`
`   :id: REQ_1`

`.. req:: My second requirement`
`   :id: REQ_2`
   
`.. spec:: My spec`
`   :id: SPEC_1`
`   :links: REQ_1; REQ_2`
   
`.. needflow::`
`   :types: spec; req`

generate in 0.3.11 this diagram

![plantuml-17e232e79c1edbd4b2664cf32fe6b3576dcd4ee3](https://user-images.githubusercontent.com/8529463/58936878-18e18d80-8771-11e9-9ff4-c0e17a9876b5.png)

the correct should be this (as is in 0.3.10 )
![plantuml-b186af44b98c1852cb203fdeb7af09d8660638a2](https://user-images.githubusercontent.com/8529463/58936969-58a87500-8771-11e9-8196-2fecee88742f.png)

**Comment by danwos** [comment]
Thanks for the bug report.

I added a fix to master.
A new release will need some days as I want to include also some other fixes and improvements.

Feel free to test the current master version and give feedback :)
