### ISSUE TITLE
needtable broken sorting and duplicate needs

### ISSUE THREAD

**Issue by ubmarco** [useblocks/sphinxcontrib-needs#93]
There is a bug in the `needtable` directive in the versions 0.3.11 and 0.3.12.
When using below configuration
```
.. needtable::
    :columns: id;title;status;incoming
    :types: story
    :tags: functional
    :style: table
    :sort_by: id
```
I'm getting strange needs sorting and also duplicate needs in my table.
See here:
Version 0.3.10
![Screenshot_2019-06-25_14-59-36](https://user-images.githubusercontent.com/839934/60100577-4ca14900-975a-11e9-8496-ffcbd9ea11c6.png)

Version 0.3.11
![Screenshot_2019-06-25_15-00-35](https://user-images.githubusercontent.com/839934/60100585-5034d000-975a-11e9-9493-37387c609161.png)

**Comment by danwos** [comment]
Found the bug and fixed it.
For sorting, needtable now provides a sort mechanism.
If not set, needs will be sorted by id.
See https://sphinxcontrib-needs.readthedocs.io/en/latest/directives/needtable.html#needtable-sort

Thanks for reporting and your patience :)
